import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';

test('estimated adjustment breakdowns, mixed medians, selection and release continuity',async({page},info)=>{
 await page.goto('/property/100/compare?view=adjusted');
 const adjusted=page.getByRole('region',{name:'ParcelSavvy estimated adjusted values'});
 await expect(page.getByRole('heading',{name:'Compare similar homes',exact:true})).toBeVisible();
 await expect(page.getByRole('button',{name:'Estimated adjusted values',exact:true})).toHaveAttribute('aria-pressed','true');
 await expect(page.locator('#comparison-view-description')).toHaveText('Reported values are the Appraisal District’s market values for these homes. Estimated adjusted values use adjustment logic the district provided through open records to account for recorded differences between each home and yours. ParcelSavvy calculates these estimates; they are not the district’s official results.');
 await expect(page.locator('#comparison-view-description')).toHaveCount(1);
 await expect(adjusted).toContainText('3 of 3 selected properties have estimated adjusted values');
 await expect(adjusted).toContainText('PS-ADJ-2026.3');
 await expect(adjusted).toContainText('$460,000');
 await expect(adjusted).toContainText('Reported median before adjustments: $460,000');
 await expect(adjusted.locator('.comparison-summary').getByText('Not available',{exact:true})).toHaveCount(0);
 const first=page.getByRole('button',{name:'View breakdown · 120 CYPRESS ST →',exact:true});
 await expect(first).toHaveAttribute('aria-expanded','false');
 await expect(page.locator('#adjustment-breakdown')).toHaveCount(0);
 await first.focus();await page.keyboard.press('Enter');
 await expect(page.getByRole('heading',{name:'Adjustment breakdown · 120 CYPRESS ST',exact:true})).toBeFocused();
 await expect(page.locator('#adjustment-breakdown')).toContainText('$400,000 + $0 = $400,000');
 await expect(page.locator('#adjustment-breakdown')).toContainText('Same reported class; $0 follows the Appraisal District’s worked same-class comparisons.');
 await expect(page.locator('#adjustment-breakdown')).toContainText('Your living area (sq ft)2,000');
 await expect(adjusted).toContainText('$4,577 below');
 await expect(adjusted).toContainText('3 of 3 selected properties');
 await page.keyboard.press('Escape');
 await expect(page.locator('#adjustment-breakdown')).toHaveCount(0);
 await expect(first).toBeFocused();
 const adjustedMethod=page.getByText('How adjusted values work',{exact:true});
 await expect(adjustedMethod).toHaveCount(1);
 await adjustedMethod.focus();await page.keyboard.press('Enter');
 await expect(adjustedMethod.locator('..')).toHaveAttribute('open','');
 await expect(page.getByText(/review every input, signed amount, assumption, formula, and source/)).toBeVisible();
 await expect(page.getByText('For parcels with multiple improvements, the highest-reported-value improvement supplies living area, class, and depreciation inputs; non-living details and other buildings are adjusted separately.',{exact:false})).toBeVisible();
 await expect(page.getByText('Each adjustment is truncated to whole dollars after unit rates are rounded to cents.',{exact:false})).toBeVisible();
 await first.focus();await page.keyboard.press('Enter');
 await expect(page.locator('#adjustment-breakdown')).toBeVisible();
 await page.getByRole('button',{name:'Close breakdown ×',exact:true}).click();
 await expect(first).toBeFocused();
 const violations=(await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations;
 expect(violations).toEqual([]);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.evaluate(()=>{document.documentElement.style.fontSize='200%';});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.evaluate(()=>{document.documentElement.style.fontSize='';window.scrollTo(0,0);});
 const capture=info.outputPath('adjusted-comparison-page.png');await page.screenshot({path:capture,fullPage:true});await info.attach('Adjusted comparison page',{path:capture,contentType:'image/png'});
 await page.getByRole('button',{name:'Edit selection (3)',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Choose homes to compare',exact:true})).toBeVisible();
 await expect(page.getByRole('group',{name:'Comparison values'})).toHaveCount(0);
 await page.getByRole('button',{name:'Clear selections',exact:true}).click();
 await expect(page.getByText('0 of 10 properties selected',{exact:true})).toBeVisible();
 await page.getByRole('checkbox',{name:'Select 120 CYPRESS ST (120)',exact:true}).check();
 await page.getByRole('complementary',{name:'Your comparison set'}).getByRole('button',{name:'Apply selection',exact:true}).click();
 await expect(page.getByRole('button',{name:'Estimated adjusted values',exact:true})).toHaveAttribute('aria-pressed','true');
 await page.getByRole('button',{name:'Reported values',exact:true}).click();
 await expect(page).toHaveURL(/selected=120/);
 await expect(page).toHaveURL(/view=reported/);
 await expect(page.getByRole('button',{name:'Reported values',exact:true})).toHaveAttribute('aria-pressed','true');
 await page.goBack();
 await expect(page.getByRole('button',{name:'Estimated adjusted values',exact:true})).toHaveAttribute('aria-pressed','true');
 await expect(adjusted).toContainText('1 of 1 selected properties');
 await page.reload();await expect(adjusted).toContainText('1 of 1 selected properties');
 await page.getByLabel('Assessment release').selectOption('22222222-2222-4222-8222-222222222222');
 await expect(adjusted).toContainText('$390,000');
 await expect(adjusted).toContainText('2025 certified');
 await expect(adjusted).toContainText('Estimate method: Appraisal District formulas');
 await expect(page.getByText('2025 matching tolerances have not been verified.',{exact:false})).toBeVisible();
 await expect(page.getByText('Adjustment inputs are separate:',{exact:false})).toBeVisible();
 const caveat=info.outputPath('prior-year-matching-caveat.png');await page.screenshot({path:caveat,fullPage:true});await info.attach('Prior-year matching caveat',{path:caveat,contentType:'image/png'});
 await page.getByRole('button',{name:'View breakdown · 120 CYPRESS ST →',exact:true}).click();
 await expect(page.locator('#adjustment-breakdown')).toContainText('2025');
 await expect(page.locator('#adjustment-breakdown')).toContainText('R3');
 await page.keyboard.press('Escape');
 await expect(page.getByRole('button',{name:'Estimated adjusted values',exact:true})).toHaveAttribute('aria-pressed','true');
});

test('additional improvements contribute to estimates without review flags',async({page},info)=>{
 await page.goto('/property/123/compare?view=adjusted&selected=120');
 const adjusted=page.getByRole('region',{name:'ParcelSavvy estimated adjusted values'});
 await expect(adjusted).toContainText('1 of 1 selected properties have estimated adjusted values');
 await expect(adjusted).not.toContainText('Needs review');
 await page.getByRole('button',{name:'View breakdown · 120 CYPRESS ST →',exact:true}).click();
 await expect(page.locator('#adjustment-breakdown')).toContainText('$627,149');
 await expect(adjusted).not.toContainText('Estimate withheld pending review');
 await expect(adjusted).toContainText('Estimated adjusted value');
 await expect(adjusted).not.toContainText('Subtotal of available adjustments');
 const violations=(await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations;
 expect(violations).toEqual([]);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.evaluate(()=>{document.documentElement.style.fontSize='200%';});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.evaluate(()=>{document.documentElement.style.fontSize='';});
 await page.screenshot({path:info.outputPath('additional-improvement-estimate.png'),fullPage:true});
});

test('missing reported inputs withhold estimates without producing a zero median',async({page})=>{
 test.skip(page.viewportSize()!.width!==1440,'One deterministic edge-state check.');
 await page.goto('/property/100/compare?view=adjusted&selected=123');
 const adjusted=page.getByRole('region',{name:'ParcelSavvy estimated adjusted values'});
 await expect(adjusted).toContainText('0 of 1 selected properties have estimated adjusted values');
 await expect(adjusted).toContainText('No complete estimates are available');
 await expect(adjusted.locator('.comparison-summary')).not.toContainText('$0');
 await expect(adjusted).toContainText('Additional structure');
 await page.getByRole('button',{name:'View breakdown · 123 PINE ST →',exact:true}).click();
 await expect(page.locator('#adjustment-breakdown')).toContainText('Subtotal of available adjustments');
 await page.keyboard.press('Escape');
});
