import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';

test('estimated adjustment breakdowns, mixed medians, selection and release continuity',async({page},info)=>{
 await page.goto('/property/100/compare?view=adjusted');
 const adjusted=page.getByRole('region',{name:'ParcelSavvy estimated adjusted values'});
 await expect(page.getByRole('heading',{name:'Your property comparison',exact:true})).toBeVisible();
 await expect(page.getByRole('button',{name:'Estimated adjusted values',exact:true})).toHaveAttribute('aria-pressed','true');
 await expect(adjusted).toContainText('3 of 3 selected properties have estimated adjusted values');
 await expect(adjusted).toContainText('Not an official Appraisal District appraisal.');
 await expect(adjusted).toContainText('PS-ADJ-2026.2');
 await expect(adjusted).toContainText('$460,000');
 await expect(adjusted).toContainText('Your property: $10,000 below (2.2% lower)');
 await expect(adjusted.locator('.comparison-summary').getByText('Not available',{exact:true})).toHaveCount(0);
 const first=page.getByRole('button',{name:'Adjustment breakdown · 120 CYPRESS ST',exact:true});
 await expect(first).toHaveAttribute('aria-expanded','true');
 await expect(page.locator('#adjustment-120')).toContainText('$400,000 + $0 = $400,000');
 await expect(page.locator('#adjustment-120')).toContainText('Same reported class; $0 follows TCAD’s worked same-class comparisons.');
 await expect(page.locator('#adjustment-120')).toContainText('Your living area (sq ft)2,000');
 await expect(adjusted).toContainText('$4,577 below');
 await expect(adjusted).toContainText('3 estimates');
 await first.focus();await page.keyboard.press('Enter');
 await expect(page.locator('#adjustment-120')).toBeHidden();
 await page.keyboard.press('Enter');
 await expect(page.locator('#adjustment-120')).toBeVisible();
 const violations=(await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations;
 expect(violations).toEqual([]);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.evaluate(()=>{document.documentElement.style.fontSize='200%';});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.evaluate(()=>{document.documentElement.style.fontSize='';window.scrollTo(0,0);});
 const capture=info.outputPath('adjusted-comparison-page.png');await page.screenshot({path:capture,fullPage:true});await info.attach('Adjusted comparison page',{path:capture,contentType:'image/png'});
 await page.getByRole('button',{name:'Edit comparison set (3)',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Choose comparison properties',exact:true})).toBeVisible();
 await expect(page.getByRole('group',{name:'Comparison values'})).toHaveCount(0);
 await page.getByRole('button',{name:'Clear selections',exact:true}).click();
 await expect(page.getByRole('button',{name:'Compare selected properties',exact:true})).toBeDisabled();
 await page.getByRole('checkbox',{name:'Select 120 CYPRESS ST (120)',exact:true}).check();
 await page.getByRole('button',{name:'Compare selected properties',exact:true}).click();
 await expect(page.getByRole('button',{name:'Reported values',exact:true})).toHaveAttribute('aria-pressed','true');
 await page.getByRole('button',{name:'Estimated adjusted values',exact:true}).click();
 await expect(adjusted).toContainText('1 of 1 selected properties');
 await page.reload();await expect(adjusted).toContainText('1 of 1 selected properties');
 await page.getByLabel('Assessment release').selectOption('22222222-2222-4222-8222-222222222222');
 await expect(adjusted).toContainText('$390,000');
 await expect(adjusted).toContainText('2025 certified');
 await expect(adjusted).toContainText('Estimate method: TCAD formulas');
 await expect(page.getByRole('button',{name:'Estimated adjusted values',exact:true})).toHaveAttribute('aria-pressed','true');
});

test('additional improvement values are visible but withheld from estimates',async({page},info)=>{
 await page.goto('/property/100/compare?view=adjusted&selected=123');
 const adjusted=page.getByRole('region',{name:'ParcelSavvy estimated adjusted values'});
 await expect(adjusted).toContainText('0 of 1 selected properties have estimated adjusted values');
 await expect(adjusted).toContainText('Needs review');
 await expect(adjusted).toContainText('How their living areas and features should be adjusted together needs review.');
 await expect(adjusted).toContainText('$627,149');
 await expect(adjusted).toContainText('Estimate withheld pending review');
 await expect(adjusted).not.toContainText('Subtotal of available adjustments');
 const violations=(await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations;
 expect(violations).toEqual([]);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.evaluate(()=>{document.documentElement.style.fontSize='200%';});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.evaluate(()=>{document.documentElement.style.fontSize='';});
 await page.screenshot({path:info.outputPath('grouping-review.png'),fullPage:true});
});
