import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
test('comparison selection, median, manual search, release switching and responsive access',async({page},info)=>{
 await page.goto('/property/100');
 await page.getByRole('navigation',{name:'Property tools'}).getByRole('link',{name:'Compare properties',exact:true}).click();
 await expect(page).toHaveURL(/\/property\/100\/compare/);
 await expect(page.getByRole('heading',{name:'Choose comparison properties',exact:true})).toBeVisible();
 await expect(page.getByRole('navigation',{name:'Property tools'}).locator('[aria-current="page"]')).toHaveText('Compare properties');
 await expect(page.getByRole('group',{name:'Comparison values'})).toHaveCount(0);
 await expect(page.getByRole('button',{name:'Compare selected properties',exact:true})).toHaveCSS('color','rgb(255, 255, 255)');
 await expect(page.getByLabel('Similarity tier')).toHaveValue('0');
 await expect(page.getByRole('complementary',{name:'Your comparison set'})).not.toContainText('Tier 0');
 await expect(page.getByRole('region',{name:'Suggested property table'})).not.toContainText('Possible Tier');
 const results=page.getByRole('region',{name:'Your selected properties, side by side'});
 await expect(results).toHaveCount(0);
 await page.getByRole('button',{name:'Clear selections',exact:true}).click();
 await expect(page.getByRole('button',{name:'Compare selected properties',exact:true})).toBeDisabled();
 await page.getByRole('checkbox',{name:'Select 120 CYPRESS ST (120)',exact:true}).check();
 await page.reload();
 await expect(page.getByText('1 of 10 properties selected',{exact:true})).toBeVisible();
 const add=page.getByRole('link',{name:'+ Add by address or ID',exact:true});
 await add.focus();await page.keyboard.press('Enter');
 await expect(page.locator('#comparison-search-heading')).toBeFocused();
 await page.getByLabel('Property address or ID',{exact:true}).fill('PINE');
 await page.getByRole('button',{name:'Search properties',exact:true}).click();
 await page.getByRole('checkbox',{name:'Select 123 PINE ST (123)',exact:true}).check();
 await expect(page.getByText('2 of 10 properties selected',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Remove 123 PINE ST (123)',exact:true}).click();
 await page.getByRole('link',{name:'How matching works',exact:true}).focus();await page.keyboard.press('Enter');
 await expect(page.locator('#comparison-rules-heading')).toBeFocused();
 await expect(page.getByText('What ParcelSavvy can check today:',{exact:true})).toBeVisible();
 await page.locator('#comparison-rules-heading').click();
 await page.getByRole('button',{name:'Compare selected properties',exact:true}).focus();await page.keyboard.press('Enter');
 await expect(page).toHaveURL(/step=results/);await expect(page).toHaveURL(/view=reported/);
 await expect(page.getByRole('heading',{name:'Your property comparison',exact:true})).toBeVisible();
 await expect(page.getByRole('button',{name:'Reported values',exact:true})).toHaveAttribute('aria-pressed','true');
 await expect(page.getByRole('button',{name:'Estimated adjusted values',exact:true})).toBeVisible();
 await expect(results).toContainText('$50,000 above');
 await expect(results).toContainText('12.5% higher');
 await expect(results).toContainText('Tier 0');
 await page.getByRole('button',{name:'Edit comparison set (1)',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Choose comparison properties',exact:true})).toBeVisible();
 await expect(page.getByText('1 of 10 properties selected',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Compare selected properties',exact:true}).click();
 const violations=(await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations;
 expect(violations).toEqual([]);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.evaluate(()=>{document.documentElement.style.fontSize='200%';});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.evaluate(()=>{document.documentElement.style.fontSize='';window.scrollTo(0,0);});
 const capture=info.outputPath('comparison-page.png');await page.screenshot({path:capture,fullPage:true});await info.attach('Comparison page',{path:capture,contentType:'image/png'});
 await page.getByLabel('Assessment release').selectOption('22222222-2222-4222-8222-222222222222');
 await expect(results).toContainText('$30,000 above');
 await expect(results).toContainText('2025 certified');
 await expect(page.getByText('2025 rules have not been verified',{exact:false})).toBeVisible();
 await page.goto('/property/103/compare');await expect(page.getByRole('heading',{name:"Let’s try another address"})).toBeVisible();
});
