import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
test('comparison selection, median, manual search, release switching and responsive access',async({page},info)=>{
 test.setTimeout(60_000);
 await page.goto('/property/100');
 await page.getByRole('navigation',{name:'Property tools'}).getByRole('link',{name:'Compare properties',exact:true}).click();
 await expect(page).toHaveURL(/\/property\/100\/compare/);
 await expect(page.getByRole('heading',{name:'Choose homes to compare',exact:true})).toBeVisible();
 const selectionIntro='Compare your home’s market value with homes like yours. If a similar home has a lower value, take a closer look at the differences. That can help you decide whether to protest and which properties may be useful as evidence.';
 const similarityGuidance='Start with homes similar in location, size, age, and construction. Condition and other details matter too.';
 await expect(page.getByText(selectionIntro,{exact:true})).toBeVisible();
 await expect(page.getByText(similarityGuidance,{exact:true})).toBeVisible();
 await expect(page.getByRole('navigation',{name:'Property tools'}).locator('[aria-current="page"]')).toHaveText('Compare properties');
 await expect(page.getByLabel('Assessment release')).toHaveValue('11111111-1111-4111-8111-111111111111');
 for(const label of ['Preparing for','Evidence start','Evidence end'])await expect(page.getByLabel(label,{exact:true})).toHaveCount(0);
 await expect(page.getByRole('button',{name:'Apply dates',exact:true})).toHaveCount(0);
 await expect(page.getByText('Ownership changes use the selected research dates.',{exact:false})).toHaveCount(0);
 await expect(page.getByRole('group',{name:'Comparison values'})).toHaveCount(0);
 await expect(page.getByRole('complementary',{name:'Your comparison set'}).getByRole('button',{name:'Apply selection',exact:true})).toHaveCSS('color','rgb(255, 255, 255)');
 await expect(page.getByLabel('Similarity tier')).toHaveValue('0');
 await expect(page.getByRole('complementary',{name:'Your comparison set'})).not.toContainText('Tier 0');
 await expect(page.getByRole('region',{name:'Suggested property table'})).not.toContainText('Possible Tier');
 const tierGuidance='Match tiers compare recorded market area, construction class, living area, and age. They are a starting point, not the Appraisal District’s complete comparable-property score. Condition and other eligibility factors remain unverified.';
 await expect(page.getByText(tierGuidance,{exact:true})).toBeHidden();
 await expect(page.getByText(tierGuidance,{exact:true})).toHaveCount(1);
 await expect(page.getByText('How matching works',{exact:true})).toHaveCount(2);
 await expect(page.locator('details.comparison-method > summary').filter({hasText:'How matching works'})).toHaveCount(1);
 await expect(page.getByText('Condition and other eligibility factors remain unverified.',{exact:false})).toHaveCount(1);
 const selection=page.getByRole('complementary',{name:'Your comparison set'});
 await expect(selection.getByText('Your draft does not replace the active comparison until you apply it. Cancel keeps your active comparison.',{exact:false})).toBeVisible();
 await expect(page.getByText(/deducts 15 points/)).toHaveCount(0);
 await expect(page.getByText(/undivided-interest children/)).toHaveCount(0);
 const results=page.getByRole('region',{name:'Reported comparison values'});
 await expect(results).toHaveCount(0);
 await page.getByRole('button',{name:'Clear selections',exact:true}).click();
 await expect(page.getByText('0 of 10 properties selected',{exact:true})).toBeVisible();
 await page.getByRole('checkbox',{name:'Select 120 CYPRESS ST (120)',exact:true}).check();
 await page.getByLabel('Similarity tier').selectOption('1');
 await page.getByLabel('Similarity tier').selectOption('0');
 await expect(page.getByText('1 of 10 properties selected',{exact:true})).toBeVisible();
 const add=page.getByRole('link',{name:'+ Add by address or ID',exact:true});
 await add.focus();await page.keyboard.press('Enter');
 await expect(page.locator('#comparison-search-heading')).toBeFocused();
 await page.getByLabel('Property address or ID',{exact:true}).fill('PINE');
 await page.getByRole('button',{name:'Search properties',exact:true}).click();
 await page.getByRole('checkbox',{name:'Select 123 PINE ST (123)',exact:true}).check();
 await expect(page.getByText('2 of 10 properties selected',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Remove 123 PINE ST (123)',exact:true}).click();
 await page.getByRole('link',{name:'How matching works',exact:true}).focus();await page.keyboard.press('Enter');
 await expect(page.getByText(tierGuidance,{exact:true})).toBeVisible();
 await expect(page.locator('#comparison-rules-heading')).toBeFocused();
 await expect(page.locator('#comparison-rules-heading')).toHaveAccessibleName('How matching works');
 await expect(page.getByText('Limits of the match:',{exact:true})).toBeVisible();
 await expect(page.getByRole('link',{name:'Read Data & methodology',exact:true})).toHaveAttribute('href','/methodology');
 await page.locator('#comparison-rules-heading').click();
 await page.getByRole('complementary',{name:'Your comparison set'}).getByRole('button',{name:'Apply selection',exact:true}).focus();await page.keyboard.press('Enter');
 await expect(page).toHaveURL(/step=results/);await expect(page).toHaveURL(/view=reported/);
 await expect(page.getByRole('heading',{name:'Compare similar homes',exact:true})).toBeVisible();
 await expect(page.getByRole('button',{name:'Reported values',exact:true})).toHaveAttribute('aria-pressed','true');
 await expect(page.getByRole('button',{name:'Estimated adjusted values',exact:true})).toBeVisible();
 const viewExplanation=page.locator('#comparison-view-description');
 await expect(viewExplanation).toHaveText('Reported values are the Appraisal District’s market values for these homes. Estimated adjusted values use adjustment logic the district provided through open records to account for recorded differences between each home and yours. ParcelSavvy calculates these estimates; they are not the district’s official results.');
 await expect(viewExplanation).toHaveCount(1);
 await expect(page.getByRole('group',{name:'Comparison values'})).toHaveAttribute('aria-describedby','comparison-view-description');
 await expect(page.getByText(tierGuidance,{exact:true})).toBeHidden();
 await expect(page.getByText(selectionIntro,{exact:true})).toHaveCount(0);
 await expect(page.getByText(similarityGuidance,{exact:true})).toHaveCount(0);
 await expect(page.getByText('Your draft does not replace the active comparison until you apply it.',{exact:false})).toHaveCount(0);
 await expect(results).toContainText('$50,000 above');
 await expect(results).toContainText('12.5% above');
 await page.reload();await expect(page.getByRole('button',{name:'Edit selection (1)',exact:true})).toBeVisible();await expect(viewExplanation).toBeVisible();
 await expect(results).toContainText('Tier 0');
 await page.getByRole('button',{name:'Edit selection (1)',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Choose homes to compare',exact:true})).toBeFocused();
 await page.getByRole('button',{name:'Clear selections',exact:true}).click();
 await page.getByRole('button',{name:'Cancel changes',exact:true}).click();
 await expect(page.getByRole('button',{name:'Edit selection (1)',exact:true})).toBeFocused();
 await expect(results).toContainText('$50,000 above');
 await page.getByRole('button',{name:'Edit selection (1)',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Choose homes to compare',exact:true})).toBeVisible();
 await expect(page.getByText('1 of 10 properties selected',{exact:true})).toBeVisible();
 const editor=info.outputPath('comparison-editor.png');await page.screenshot({path:editor,fullPage:true});await info.attach('Selection editor',{path:editor,contentType:'image/png'});
 await page.getByRole('complementary',{name:'Your comparison set'}).getByRole('button',{name:'Apply selection',exact:true}).click();
 const violations=(await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations;
 expect(violations).toEqual([]);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.evaluate(()=>{document.documentElement.style.fontSize='200%';});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.evaluate(()=>{document.documentElement.style.fontSize='';window.scrollTo(0,0);});
 const capture=info.outputPath('comparison-page.png');await page.screenshot({path:capture,fullPage:true});await info.attach('Comparison page',{path:capture,contentType:'image/png'});
 await page.getByLabel('Assessment release').selectOption('22222222-2222-4222-8222-222222222222');
 await expect(viewExplanation).toBeVisible();
 await expect(results).toContainText('$30,000 above');
 await expect(results).toContainText('2025 certified');
 await page.locator('#comparison-rules-heading').click();
 await expect(page.getByText('2025 matching tolerances have not been verified',{exact:false})).toBeVisible();
 await page.goto('/property/103/compare');await expect(page.getByRole('heading',{name:"Let’s try another address"})).toBeVisible();
});

test('draft limit, cancellation, empty sets and unavailable saved properties',async({page})=>{
 test.skip(page.viewportSize()!.width!==1440,'Bounded state coverage; the main flow checks responsive widths.');
 await page.goto('/property/100/compare?step=results&selected=120');
 await page.getByRole('button',{name:'Edit selection (1)',exact:true}).click();
 await page.route('**/api/property/100/comparisons?*',async route=>route.fulfill({json:{status:'ok',data:{anchor_id:'11111111-1111-4111-8111-111111111111',release:{dataset_id:'11111111-1111-4111-8111-111111111111'},search_has_more:false,matches:Array.from({length:11},(_,i)=>({property_id:String(1900+i),address:`TEST ${i}`,city:'FIXTURE',property_type:'R',market_value:400000,land_value:100000,land_acres:1,neighborhood:'T2450',living_area:2000,class_code:'R3',year_built:2014,main_buildings:1}))}}}));
 await page.getByLabel('Property address or ID',{exact:true}).fill('TEST');
 await page.getByRole('button',{name:'Search properties',exact:true}).click();
 for(let i=0;i<9;i++)await page.getByRole('checkbox',{name:`Select TEST ${i} (${1900+i})`,exact:true}).check();
 await expect(page.getByText('10 of 10 properties selected',{exact:true})).toBeVisible();
 await expect(page.getByRole('checkbox',{name:'Select TEST 9 (1909)',exact:true})).toBeDisabled();
 await page.getByLabel('Similarity tier').selectOption('7');
 await expect(page.getByText('10 of 10 properties selected',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Cancel changes',exact:true}).click();
 await expect(page.getByRole('button',{name:'Edit selection (1)',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Edit selection (1)',exact:true}).click();
 await page.getByRole('button',{name:'Clear selections',exact:true}).click();
 await page.getByRole('complementary',{name:'Your comparison set'}).getByRole('button',{name:'Apply selection',exact:true}).click();
 await expect(page.getByText('No homes selected. Use Edit selection to build your comparison.',{exact:true})).toBeVisible();
 await page.goto('/property/100/compare?step=results&selected=120,121');
 await page.getByLabel('Assessment release').selectOption('22222222-2222-4222-8222-222222222222');
 await expect(page.getByText('Some saved selections are unavailable in this release and were left out.',{exact:true})).toBeVisible();
 await expect(page.getByRole('button',{name:'Edit selection (1)',exact:true})).toBeVisible();
});


test('ownership disclosures require a recorded change in both value modes',async({page},info)=>{
 test.skip(page.viewportSize()!.width===768,'Mixed ownership evidence at desktop and narrow mobile.');
 await page.goto('/property/100/compare?step=results&selected=120,121,122&targetYear=2027&evidenceStart=2026-06-01&evidenceEnd=2026-06-30&activityYear=2026');
 const reported=page.getByRole('region',{name:'Reported comparison values'});
 await expect(reported.locator('.comparison-deed')).toHaveCount(1);
 await expect(reported.locator('.comparison-deed summary')).toHaveText('Ownership change · 2025-06-20');
 await expect(reported).toContainText('$460,000');
 await expect(page.getByText('Ownership-change coverage is unavailable for some selected properties.',{exact:false})).toBeVisible();
 await reported.locator('.comparison-deed summary').focus();await page.keyboard.press('Enter');
 await expect(reported.locator('.comparison-deed')).toContainText('Recorded date: 2025-06-20');
 await expect(reported.locator('.comparison-deed')).toContainText('does not confirm that the property was sold');
 await expect(reported.locator('.comparison-deed')).toContainText('calendar year before the 2026 assessment release: 2025-01-01–2025-12-31');
 await expect(reported.locator('.comparison-deed')).toContainText('Source coverage:');
 await page.screenshot({path:info.outputPath('mixed-ownership-reported.png'),fullPage:true});
 await page.getByRole('button',{name:'Estimated adjusted values',exact:true}).click();
 const adjusted=page.getByRole('region',{name:'ParcelSavvy estimated adjusted values'});
 await expect(adjusted).toBeVisible();
 const normalized=new URL(page.url());for(const key of ['targetYear','evidenceStart','evidenceEnd','activityYear'])expect(normalized.searchParams.has(key)).toBe(false);
 await expect(adjusted.locator('.comparison-compact-row .comparison-deed')).toHaveCount(1);
 await expect(adjusted).toContainText('3 of 3 selected properties');
 await expect(adjusted).toContainText('$460,000');
 for(const id of ['120','121','122']){
  await page.getByRole('button',{name:new RegExp('View breakdown · '+id+' ')}).click();
  await expect(page.locator('#adjustment-breakdown').locator('.comparison-deed')).toHaveCount(id==='120'?1:0);
  await page.keyboard.press('Escape');
 }
 await page.screenshot({path:info.outputPath('mixed-ownership-adjusted.png'),fullPage:true});
 await expect(page.getByRole('button',{name:'Edit selection (3)',exact:true})).toBeVisible();
 await expect(page.getByText(/No deed clue|Deed evidence unavailable/)).toHaveCount(0);
 await page.getByLabel('Assessment release').selectOption('22222222-2222-4222-8222-222222222222');
 await expect(page.locator('.comparison-deed')).toHaveCount(0);
 await expect(page.getByText('Ownership-change coverage is unavailable for some selected properties.',{exact:false})).toBeVisible();
 await expect(page.getByText(/No ownership change|No transfer/)).toHaveCount(0);
});
