import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
test('comparison selection, median, manual search, release switching and responsive access',async({page},info)=>{
 await page.goto('/property/100');
 await page.getByRole('navigation',{name:'Property tools'}).getByRole('link',{name:'Compare properties',exact:true}).click();
 await expect(page).toHaveURL(/\/property\/100\/compare/);
 await expect(page.getByRole('heading',{name:'Choose homes to compare',exact:true})).toBeVisible();
 await expect(page.getByRole('navigation',{name:'Property tools'}).locator('[aria-current="page"]')).toHaveText('Compare properties');
 await expect(page.getByRole('group',{name:'Comparison values'})).toHaveCount(0);
 await expect(page.getByRole('complementary',{name:'Your comparison set'}).getByRole('button',{name:'Apply selection',exact:true})).toHaveCSS('color','rgb(255, 255, 255)');
 await expect(page.getByLabel('Similarity tier')).toHaveValue('0');
 await expect(page.getByRole('complementary',{name:'Your comparison set'})).not.toContainText('Tier 0');
 await expect(page.getByRole('region',{name:'Suggested property table'})).not.toContainText('Possible Tier');
 const results=page.getByRole('region',{name:'Reported comparison values'});
 await expect(results).toHaveCount(0);
 await page.getByRole('button',{name:'Clear selections',exact:true}).click();
 await expect(page.getByText('0 of 10 properties selected',{exact:true})).toBeVisible();
 await page.getByRole('checkbox',{name:'Select 120 CYPRESS ST (120)',exact:true}).check();
 await page.getByLabel('Similarity tier').selectOption('1');
 await page.getByLabel('Similarity tier').selectOption('0');
 await expect(page.getByText('1 of 10 properties selected',{exact:true})).toBeVisible();
 const add=page.getByRole('link',{name:'+ Add by address or ID',exact:true});
 await add.focus();await page.keyboard.press('Enter');
 await expect(page.locator('#comparison-search-heading')).toBeFocused();
 await page.getByLabel('Property address or ID',{exact:true}).fill('PINE');
 await page.getByRole('button',{name:'Search properties',exact:true}).click();
 await page.getByRole('checkbox',{name:'Select 123 PINE ST (123)',exact:true}).check();
 await expect(page.getByText('2 of 10 properties selected',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Remove 123 PINE ST (123)',exact:true}).click();
 await page.getByRole('link',{name:'How matching works',exact:true}).focus();await page.keyboard.press('Enter');
 await expect(page.locator('#comparison-rules-heading')).toBeFocused();
 await expect(page.getByText('What ParcelSavvy can check today:',{exact:true})).toBeVisible();
 await page.locator('#comparison-rules-heading').click();
 await page.getByRole('complementary',{name:'Your comparison set'}).getByRole('button',{name:'Apply selection',exact:true}).focus();await page.keyboard.press('Enter');
 await expect(page).toHaveURL(/step=results/);await expect(page).toHaveURL(/view=reported/);
 await expect(page.getByRole('heading',{name:'Compare similar homes',exact:true})).toBeVisible();
 await expect(page.getByRole('button',{name:'Reported values',exact:true})).toHaveAttribute('aria-pressed','true');
 await expect(page.getByRole('button',{name:'Estimated adjusted values',exact:true})).toBeVisible();
 await expect(results).toContainText('$50,000 above');
 await expect(results).toContainText('12.5% above');
 await page.reload();await expect(page.getByRole('button',{name:'Edit selection (1)',exact:true})).toBeVisible();
 await expect(results).toContainText('Tier 0');
 await page.getByRole('button',{name:'Edit selection (1)',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Choose homes to compare',exact:true})).toBeFocused();
 await page.getByRole('button',{name:'Clear selections',exact:true}).click();
 await page.getByRole('button',{name:'Cancel changes',exact:true}).click();
 await expect(page.getByRole('button',{name:'Edit selection (1)',exact:true})).toBeFocused();
 await expect(results).toContainText('$50,000 above');
 await page.getByRole('button',{name:'Edit selection (1)',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Choose homes to compare',exact:true})).toBeVisible();
 await expect(page.getByText('1 of 10 properties selected',{exact:true})).toBeVisible();
 const editor=info.outputPath('comparison-editor.png');await page.screenshot({path:editor,fullPage:true});await info.attach('Selection editor',{path:editor,contentType:'image/png'});
 await page.getByRole('complementary',{name:'Your comparison set'}).getByRole('button',{name:'Apply selection',exact:true}).click();
 const violations=(await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations;
 expect(violations).toEqual([]);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.evaluate(()=>{document.documentElement.style.fontSize='200%';});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.evaluate(()=>{document.documentElement.style.fontSize='';window.scrollTo(0,0);});
 const capture=info.outputPath('comparison-page.png');await page.screenshot({path:capture,fullPage:true});await info.attach('Comparison page',{path:capture,contentType:'image/png'});
 await page.getByLabel('Assessment release').selectOption('22222222-2222-4222-8222-222222222222');
 await expect(results).toContainText('$30,000 above');
 await expect(results).toContainText('2025 certified');
 await expect(page.getByText('2025 rules have not been verified',{exact:false})).toBeVisible();
 await page.goto('/property/103/compare');await expect(page.getByRole('heading',{name:"Let’s try another address"})).toBeVisible();
});

test('draft limit, cancellation, empty sets and unavailable saved properties',async({page})=>{
 test.skip(page.viewportSize()!.width!==1440,'Bounded state coverage; the main flow checks responsive widths.');
 await page.goto('/property/100/compare?step=results&selected=120');
 await page.getByRole('button',{name:'Edit selection (1)',exact:true}).click();
 await page.route('**/api/property/100/comparisons?*',async route=>route.fulfill({json:{status:'ok',data:{anchor_id:'11111111-1111-4111-8111-111111111111',release:{dataset_id:'11111111-1111-4111-8111-111111111111'},search_has_more:false,matches:Array.from({length:11},(_,i)=>({property_id:String(1900+i),address:`TEST ${i}`,city:'FIXTURE',property_type:'R',market_value:400000,land_value:100000,land_acres:1,neighborhood:'T2450',living_area:2000,class_code:'R3',year_built:2014,main_buildings:1}))}}}));
 await page.getByLabel('Property address or ID',{exact:true}).fill('TEST');
 await page.getByRole('button',{name:'Search properties',exact:true}).click();
 for(let i=0;i<9;i++)await page.getByRole('checkbox',{name:`Select TEST ${i} (${1900+i})`,exact:true}).check();
 await expect(page.getByText('10 of 10 properties selected',{exact:true})).toBeVisible();
 await expect(page.getByRole('checkbox',{name:'Select TEST 9 (1909)',exact:true})).toBeDisabled();
 await page.getByLabel('Similarity tier').selectOption('7');
 await expect(page.getByText('10 of 10 properties selected',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Cancel changes',exact:true}).click();
 await expect(page.getByRole('button',{name:'Edit selection (1)',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Edit selection (1)',exact:true}).click();
 await page.getByRole('button',{name:'Clear selections',exact:true}).click();
 await page.getByRole('complementary',{name:'Your comparison set'}).getByRole('button',{name:'Apply selection',exact:true}).click();
 await expect(page.getByText('No homes selected. Use Edit selection to build your comparison.',{exact:true})).toBeVisible();
 await page.goto('/property/100/compare?step=results&selected=120,121&release=22222222-2222-4222-8222-222222222222');
 await expect(page.getByText('Some saved selections are unavailable in this release and were left out.',{exact:true})).toBeVisible();
 await expect(page.getByRole('button',{name:'Edit selection (1)',exact:true})).toBeVisible();
});
