import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import {execFileSync} from 'node:child_process';
const scope=(selected:string[])=>new URLSearchParams({targetYear:'2027',evidenceStart:'2026-01-01',evidenceEnd:'2026-12-31',activityType:'single_family',activitySort:'address',activitySelected:JSON.stringify(selected)});
const pdfText=(path:string)=>JSON.parse(execFileSync('python3',['-c','from pypdf import PdfReader; import json,sys; print(json.dumps([p.extract_text() for p in PdfReader(sys.argv[1]).pages]))',path],{encoding:'utf8'})) as string[];
test('PAR-29 populated and long shortlist reports preserve every selected record',async({page},info)=>{
 test.skip(info.project.name!=='width-1440','Two Letter cases and one A4 fallback.');test.setTimeout(120_000);
 for(const [id,name,selected] of [['9200','populated',['120:s:2','123:j:7']],['9290','long-shortlist',Array.from({length:24},(_,i)=>`${9400+i}:j:long${i}`)]] as const){
  await page.goto(`/property/${id}/neighborhood/print?${scope([...selected])}`);await expect(page.getByRole('heading',{name:'Your neighborhood, in context.',exact:true})).toBeVisible();await page.evaluate(()=>document.fonts.ready);
  await expect(page.locator('.activity-print tbody tr')).toHaveCount(selected.length);await expect(page.locator('.nbr-story')).toContainText('12 matched homes');await expect(page.locator('.nbr-story .neighborhood-story-stage')).toHaveCount(3);await expect(page.locator('.nbr-outcome')).toContainText('12 / 12');
  await expect(page.locator('.print-property-facts')).toContainText('Subdivision on record');await expect(page.locator('.print-property-facts')).toContainText('Current eligible group population');await expect(page.locator('.print-property-facts')).toContainText('2026 certified · Jul 18, 2026');await expect(page.locator('.print-group-note')).toContainText('can differ from the subdivision');
  const cap=page.locator('.nbr-cap-progression');await expect(cap.getByRole('heading',{name:'What happened with the cap?'})).toBeVisible();await expect(cap.locator('li strong')).toHaveText(['12 of 12','12 of those 12','10 of those 12']);await expect(cap).toContainText('These stages follow the same 12 homes that started above the cap.');
  const agents=page.locator('.neighborhood-agent-activity');await expect(agents.getByRole('heading',{name:'Protest agent activity in this market area'})).toBeVisible();await expect(agents.locator('.neighborhood-agent-panel')).toHaveCount(2);await expect(agents).toContainText('2026 certified appraisal');await expect(agents).toContainText('2025 certified appraisal');await expect(agents).toContainText('Other agents (1)');await expect(agents).toContainText(/\d+ reduced/);await expect(agents).toContainText('not a rating of an agent’s effectiveness');await expect(agents).not.toContainText('Draft based on');
  const headings=await page.locator('.print-report h2').allTextContents();expect(headings.indexOf('What changed during 2026')).toBeLessThan(headings.indexOf('Protest agent activity in this market area'));expect(headings.indexOf('Protest agent activity in this market area')).toBeLessThan(headings.indexOf('Evidence research & selected shortlist'));
  expect((await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations).toEqual([]);
  await page.emulateMedia({media:'print'});await expect(page.locator('.print-toolbar')).toBeHidden();await expect(page.locator('.neighborhood-agent-panels')).toHaveCSS('grid-template-columns',/\d+px/);
  const path=info.outputPath(`${name}.pdf`);await page.pdf({path,preferCSSPageSize:true,printBackground:true});await info.attach(name,{path,contentType:'application/pdf'});const pages=pdfText(path);console.log(`PAR62_PAGES ${name} ${pages.length}`);expect(pages.length).toBeGreaterThanOrEqual(name==='populated'?2:5);expect(pages.length).toBeLessThanOrEqual(name==='populated'?7:9);
  for(const [i,t] of pages.entries()){expect(t.trim().length).toBeGreaterThan(120);expect(t).toContain(`Property ${id} | 2026 certified`);expect(t).toContain(`${i+1} / ${pages.length}`);expect(t).not.toContain('Back to neighborhood analysis');if(/Property\s+94\d\d/.test(t)){expect(t).toContain('Transaction dates');expect(t).toContain('Record / price');}if(/certified appraisal/.test(t)){expect(t).toContain('Agent named in records');}}
  const text=pages.join('\n');for(const key of selected)expect(text.match(new RegExp('Property\\s+'+key.split(':')[0]+'\\b','g'))).toHaveLength(1);expect(text).toContain('2027');expect(text).toContain('2026-01-01');expect(text).toContain('not proof of a sale');expect(text).not.toMatch(/NaN|Infinity/);
 }
 await page.addStyleTag({content:'@page {size:A4;} .print-report {--color-action:#333;--color-surface-info:#eee;--color-text:#111;--color-text-muted:#444;} .print-header img {filter:grayscale(1);}'});const path=info.outputPath('long-shortlist-a4-gray.pdf');await page.pdf({path,preferCSSPageSize:true,printBackground:true});await info.attach('A4 grayscale',{path,contentType:'application/pdf'});const grayPages=pdfText(path);expect(grayPages.length).toBeGreaterThanOrEqual(5);expect(grayPages.length).toBeLessThanOrEqual(9);expect(grayPages.join('\n').match(/Property\s+94\d\d\b/g)).toHaveLength(24);
 await page.goto('/property/9204/neighborhood/print?targetYear=2025&evidenceStart=2024-01-01&evidenceEnd=2024-12-31');await expect(page.locator('.print-report')).toContainText('Not available');await expect(page.locator('.print-report')).toContainText('Coverage unavailable for 2024');await expect(page.locator('.activity-print')).toContainText('No available records selected');await expect(page.locator('.neighborhood-agent-unavailable')).toContainText('A completed proposed-to-certified pair is needed');await expect(page.locator('.print-report')).not.toContainText(/NaN|Infinity|0 \/ 0/);const sparse=info.outputPath('sparse-unavailable.pdf');await page.pdf({path:sparse,preferCSSPageSize:true,printBackground:true});await info.attach('Sparse unavailable',{path:sparse,contentType:'application/pdf'});const sparsePages=pdfText(sparse);expect(sparsePages.length).toBeGreaterThanOrEqual(1);expect(sparsePages.join('\n')).toContain('Missing outcomes are not zero reductions');
});
test('PAR-29 narrow keyboard print and Back retain research and shortlist state',async({page},info)=>{
 test.skip(info.project.name!=='width-375','One narrow keyboard journey.');
 const query=scope(['120:s:2','123:j:7']);await page.goto(`/property/100/neighborhood?${query}`);
 const printLink=page.getByRole('link',{name:'Print / save PDF',exact:true});await printLink.focus();await printLink.press('Enter');await expect(page.locator('.activity-print tbody tr')).toHaveCount(2);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect((await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations).toEqual([]);
 await page.evaluate(()=>{window.print=()=>{document.body.dataset.printRequested='yes';};});const print=page.getByRole('button',{name:'Print or save as PDF'});await print.focus();await print.press('Enter');await expect(page.locator('body')).toHaveAttribute('data-print-requested','yes');
 const back=page.getByRole('link',{name:'Back to neighborhood analysis'});await expect(back).toHaveAttribute('href',`/property/100/neighborhood?${query}`);await back.focus();await back.press('Enter');await expect(page).toHaveURL(new RegExp('/property/100/neighborhood\\?'));await expect(page.locator('.activity-shortlist')).toContainText('2');
});

test('PAR-29 small cohort is count-first and chart ranges have text equivalents',async({page},info)=>{
 test.skip(info.project.name!=='width-1440','One targeted report semantics check.');
 await page.goto('/property/9203/neighborhood/print');
 const metric=page.locator('.nbr-story').getByText('Proposed vs prior certified',{exact:true}).locator('..');await expect(metric.locator('dd').first()).toHaveText('3 matched homes');
 const ranges=page.getByRole('list',{name:'Market-value ranges'});await expect(ranges.getByRole('listitem')).toHaveCount(8);await expect(ranges).toContainText('homes');await expect(ranges).toContainText('upper boundary excluded');
});

test('PAR-62 print keeps dynamic completed years and honest unavailable states',async({page},info)=>{
 test.skip(info.project.name!=='width-1440','Focused state parity at one viewport.');
 await page.goto('/property/9201/neighborhood/print');await expect(page.locator('.nbr-story')).toContainText('2026 preliminary');await expect(page.locator('.nbr-story')).toContainText('Pending certification');await expect(page.locator('.nbr-outcome')).toContainText('What changed during 2025');await expect(page.locator('.neighborhood-agent-panel')).toHaveCount(1);await expect(page.locator('.neighborhood-agent-panel')).toContainText('2025 certified appraisal');await expect(page.locator('.neighborhood-agent-activity')).not.toContainText('2026 certified appraisal');
 await page.goto('/property/100/neighborhood/print');await expect(page.locator('.neighborhood-agent-panel')).toHaveCount(1);await expect(page.locator('.neighborhood-agent-activity')).toContainText('No agent identified');
 await page.goto('/property/9205/neighborhood/print');await expect(page.locator('.nbr-cap-progression')).toContainText('Not available');await expect(page.locator('.nbr-cap-progression')).toContainText('No homes with identified protest activity have both 2026 preliminary and certified market values and a usable recorded preliminary cap.');await expect(page.locator('.print-report')).not.toContainText(/0 \/ 0|Cap rows use eligible recorded caps|Homes reduced/);
});
