import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
test('neighborhood annual story, controls, canonical links and print parity',async({page},info)=>{
 test.skip(info.project.name!=='width-1440','One complete journey; responsive checks below cover other widths.');
 await page.goto('/property/100/neighborhood');
 await expect(page.getByRole('heading',{name:'Your neighborhood, in context.',exact:true})).toBeVisible();
 await expect(page.getByRole('navigation',{name:'Property tools'}).locator('[aria-current="page"]')).toHaveText('Neighborhood');
 const groupSummary=page.locator('summary').filter({hasText:'About this group'}),groupDetails=groupSummary.locator('..');
 await expect(groupDetails).toHaveAttribute('open','');await expect(groupSummary).toHaveAttribute('aria-expanded','true');await expect(groupDetails.getByText(/Subdivision on record: GRAND MESA SECTION II\./)).toBeVisible();
 await groupSummary.focus();await page.keyboard.press('Enter');await expect(groupDetails).not.toHaveAttribute('open','');await expect(groupSummary).toHaveAttribute('aria-expanded','false');await page.keyboard.press('Enter');await expect(groupDetails).toHaveAttribute('open','');await expect(groupSummary).toHaveAttribute('aria-expanded','true');
 await expect(page.locator('.activity-controls select')).toHaveCount(2);
 await expect(page.getByRole('form',{name:'Evidence research window'})).toBeVisible();
 await expect(page.getByRole('link',{name:'Print / save PDF',exact:true})).toHaveAttribute('href',/targetYear=2027&evidenceStart=2026-01-01&evidenceEnd=2026-12-31/);
 const story=page.locator('.neighborhood-story'),stages=story.locator('.neighborhood-story-stage');
 await expect(stages).toHaveCount(3);expect(await stages.locator('h3').allTextContents()).toEqual(['Where the year started','What happened through protest season','Where the year landed']);
 const stageBoxes=await stages.evaluateAll(nodes=>nodes.map(node=>{const box=node.getBoundingClientRect();return {x:box.x,y:box.y,width:box.width};}));
 expect(stageBoxes[0].y).toBe(stageBoxes[1].y);expect(stageBoxes[1].y).toBe(stageBoxes[2].y);expect(stageBoxes[0].x+stageBoxes[0].width).toBeLessThanOrEqual(stageBoxes[1].x);expect(stageBoxes[1].x+stageBoxes[1].width).toBeLessThanOrEqual(stageBoxes[2].x);
 await expect(story).toContainText('2026 certified');
 await expect(stages.nth(0)).toContainText('2025 certified → 2026 preliminary');
 await expect(stages.nth(1)).toContainText('2026 · 2 of 5 homes');
 await expect(stages.nth(1)).toContainText('2026 · 2 of 3 homes with paired values');
 await expect(stages.nth(1)).toContainText('A lower value alone does not establish that a protest happened or caused the reduction.');
 await expect(stages.nth(2)).toContainText('Certified median market value');
 await expect(stages.nth(2)).toContainText('2026 preliminary → 2026 certified');
 await expect(stages.nth(2)).toContainText('2025 certified → 2026 certified');
 await expect(story).not.toContainText(/successful protest|protest caused/i);
 await expect(page.locator('.neighborhood-results')).toContainText('What changed during 2026');
 await expect(page.locator('.neighborhood-results')).toContainText('inferred from proposed-to-certified reductions');
 const results=page.locator('.neighborhood-results');
 await expect(results.getByText('Cap comparison uses reduced homes that started above their recorded 2026 preliminary cap, with a valid threshold.',{exact:true})).toHaveCount(1);
 await expect(results.getByText('Reduction counts use homes with both proposed and certified values.',{exact:true})).toHaveCount(1);
 await expect(results.getByText('Identified activity includes public protest records and activity inferred from proposed-to-certified reductions. Records may be incomplete; an absent entry does not establish that no protest occurred.',{exact:true})).toHaveCount(1);
 await expect(results.getByText('Homes with identified protest activity').locator('..').locator('dd')).toHaveAttribute('aria-describedby','identified-protest-activity-note');
 await expect(results.getByText('Homes receiving a reduction').locator('..').locator('dd')).toHaveAttribute('aria-describedby','reduction-denominator-note');
 await expect(results.getByText('Reduced below the recorded cap').locator('..').locator('dd')).toHaveAttribute('aria-describedby','cap-denominator-note');
 const agents=page.locator('.neighborhood-agent-activity');
 await expect(agents.getByRole('heading',{name:'Protest agent activity in this market area',exact:true})).toBeVisible();
 await expect(agents).toContainText('Most recent certified year');
 await expect(agents.getByText('Agent names come from TCAD records. Median reductions include only properties whose recorded market value fell; they are not a rating of an agent’s effectiveness. “No agent identified” does not establish who handled the protest.',{exact:true})).toBeVisible();
 await expect(agents.getByText('Activity includes recorded protests and reductions that may indicate a protest. Names use the latest available export for each year.',{exact:true})).toBeVisible();
 await expect(agents).not.toContainText('Draft based on the active July 2026 release');
 await expect(agents.getByRole('table')).toHaveCount(1);await expect(agents.getByRole('img')).not.toHaveCount(0);
 await expect(agents).toContainText(/\d+ reduced|No reduced homes/);
 await expect(page.getByText('Nearby properties are not automatically comparable.',{exact:true})).toHaveCount(1);
 await expect(page.getByText(/A deed change can be a sale or another kind of transfer/)).toHaveCount(1);
 const sections=await page.locator('.neighborhood-analysis h2').allTextContents();
 expect(sections.indexOf('What changed during 2026')).toBeLessThan(sections.indexOf('Protest agent activity in this market area'));
 expect(sections.indexOf('Protest agent activity in this market area')).toBeLessThan(sections.indexOf('Recent sales & ownership changes'));
 expect(sections.indexOf('Where your home sits')).toBeLessThan(sections.indexOf('One driver of proposed values: the market-area multiplier'));
 expect(sections.indexOf('One driver of proposed values: the market-area multiplier')).toBeLessThan(sections.indexOf('Look across years, without changing views.'));
 const mode=page.getByRole('button',{name:'Value per sq. ft.',exact:true});await mode.focus();await page.keyboard.press('Enter');
 await expect(mode).toHaveAttribute('aria-pressed','true');await expect(mode).toHaveCSS('outline-style','solid');
 await expect(page.getByRole('img',{name:/Value per square foot distribution/})).toBeVisible();
 await expect(page.locator('.neighborhood-subject-value')).toContainText('$225 / sq ft');
 await page.getByRole('button',{name:'Market value',exact:true}).click();
 const disclosure=page.locator('summary').filter({hasText:'More annual outcomes and comparisons'}),expanded=disclosure.locator('..');await disclosure.focus();await page.keyboard.press('Enter');
 await expect(disclosure).toHaveAttribute('aria-expanded','true');const outcomeTable=expanded.getByRole('table');await expect(outcomeTable).toBeVisible();
 await expect(outcomeTable.getByRole('columnheader')).toHaveText(['2026 measure','Protest activity identified','No protest activity identified']);await expect(outcomeTable.getByRole('row')).toHaveCount(5);
 await expect(expanded).toContainText('Activity includes recorded protests and reductions that may indicate a protest. No activity found does not prove no protest occurred.');
 await expect(expanded).not.toContainText('Homes reduced');await expect(expanded).not.toContainText('Started above recorded cap');await expect(expanded).not.toContainText('Reduced below recorded cap');await expect(expanded).not.toContainText('Cap rows use eligible recorded caps');
 const capProgression=expanded.locator('.neighborhood-cap-progression');await expect(capProgression.getByRole('heading',{name:'What happened with the cap?'})).toBeVisible();await expect(capProgression).toContainText('matched 2026 preliminary and certified market values');
 const capStageLabels=await capProgression.locator('li strong').allTextContents();expect(capStageLabels).toHaveLength(3);const started=capStageLabels[0].match(/^(\d+) of (\d+)$/);expect(started).not.toBeNull();expect(capStageLabels[1]).toMatch(new RegExp(`^\\d+ of those ${started![1]}$`));expect(capStageLabels[2]).toMatch(new RegExp(`^\\d+ of those ${started![1]}$`));
 await expect(capProgression).toContainText(`These stages follow the same ${started![1]} homes that started above the cap.`);await expect(expanded).not.toContainText('0 / 0');
 await page.keyboard.press('Enter');await expect(disclosure).toHaveAttribute('aria-expanded','false');
 const about=page.locator('summary').filter({hasText:'About this analysis'});await about.focus();await page.keyboard.press('Enter');await expect(about).toHaveAttribute('aria-expanded','true');
 const aboutContent=about.locator('..');
 await expect(aboutContent).toContainText('Source: Appraisal District, 2026 certified, exported Jul 18, 2026.');
 await expect(aboutContent).toContainText('Counts lead when fewer than 10 homes qualify.');
 await expect(aboutContent).toContainText('Missing values and zero denominators are unavailable, not zero percent.');
 await expect(aboutContent).toContainText('Appraisal reductions are before exemptions.');
 await expect(aboutContent).toContainText('later Appraisal District corrections may not appear here');
 await expect(aboutContent).toContainText('ParcelSavvy is independent of the Appraisal District.');
 await expect(aboutContent).toContainText('2026 certified · Jul 18, 2026:');
 await expect(page.getByText('ParcelSavvy is independent of the Appraisal District. Verify property details and official notices with the district.',{exact:true})).toHaveCount(0);
 await expect(page.getByText(/This pattern alone does not establish that a value is incorrect/)).toHaveCount(0);
 await expect(page.getByText(/These groups do not establish what an agent or protest caused/)).toHaveCount(0);
 const compare=page.getByRole('link',{name:'Compare similar homes',exact:true});await expect(compare).toHaveAttribute('href',/\/property\/100\/compare\?release=/);
 await expect(page.getByRole('link',{name:'Read the protest guide →'})).toHaveAttribute('href','/protest-guide?property=100');
 await expect(page.getByRole('link',{name:'Support this project →'})).toHaveAttribute('href','https://donate.stripe.com/6oUaEP7jn6l39fSgXg7AI00');
 await page.getByRole('link',{name:'View your home’s market value and cap →'}).click();await expect(page.locator('#exemptions-heading')).toBeVisible();
 await page.goBack();await compare.click();await expect(page).toHaveURL(/\/property\/100\/compare\?release=/);await expect(page.getByRole('navigation',{name:'Property tools'}).locator('[aria-current="page"]')).toHaveText('Compare properties');await page.goBack();
 await page.getByRole('link',{name:'Read the protest guide →'}).click();await expect(page).toHaveURL(/protest-guide\?property=100/);await page.goBack();
 expect((await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations).toEqual([]);

 await page.getByRole('link',{name:'Print / save PDF',exact:true}).click();await expect(page).toHaveURL(/\/neighborhood\/print\?targetYear=2027&evidenceStart=2026-01-01&evidenceEnd=2026-12-31$/);
 await expect(page.locator('.nbr-story')).toContainText('$450,000');await expect(page.locator('.nbr-story .neighborhood-story-stage')).toHaveCount(3);await expect(page.locator('.nbr-outcome')).toContainText('1 / 2');
 await page.evaluate(()=>{window.print=()=>{document.body.dataset.printRequested='yes';};});await page.getByRole('button',{name:'Print or save as PDF'}).click();await expect(page.locator('body')).toHaveAttribute('data-print-requested','yes');
 await page.emulateMedia({media:'print'});await expect(page.locator('.print-toolbar')).toBeHidden();
 await page.emulateMedia({media:'screen'});await page.getByRole('link',{name:'Back to neighborhood analysis'}).click();await expect(page).toHaveURL(/\/property\/100\/neighborhood\?targetYear=2027&evidenceStart=2026-01-01&evidenceEnd=2026-12-31$/);
 await page.goto('/property/103/neighborhood');await expect(page.getByRole('heading',{name:'Let’s try another address'})).toBeVisible();
});
test('neighborhood period labels, additional history and missing or small samples',async({page},info)=>{
 test.skip(info.project.name!=='width-1440','Compact state checks at one viewport.');
 await page.goto('/property/9201/neighborhood');await expect(page.locator('.neighborhood-story')).toContainText('2026 preliminary');await expect(page.locator('.neighborhood-story-stage').nth(1)).toContainText('2025 · 12 of 12 homes');await expect(page.locator('.neighborhood-story-stage').nth(2)).toContainText('Pending certification');await expect(page.locator('.neighborhood-results')).toContainText('What changed during 2025');await expect(page.locator('.neighborhood-history')).toContainText('reduced by at least 10% in 2025');
 await page.goto('/property/9202/neighborhood');const more=page.locator('summary').filter({hasText:'More available year pairs'});await more.click();await expect(page.getByRole('heading',{name:'Proposed values: 2024 → 2025'})).toBeVisible();
 await page.goto('/property/9203/neighborhood');await expect(page.locator('.neighborhood-carry .neighborhood-big')).toHaveText('3 of 3 homes back at or above the prior proposal');
 await page.goto('/property/9205/neighborhood');await expect(page.locator('.neighborhood-carry .neighborhood-big')).toHaveText('Not available');await expect(page.locator('.neighborhood-carry')).toContainText('No homes with a qualifying reduction');const unavailableMore=page.locator('summary').filter({hasText:'More annual outcomes and comparisons'});await unavailableMore.click();const unavailableCap=unavailableMore.locator('..').locator('.neighborhood-cap-progression');await expect(unavailableCap).toContainText('Not available');await expect(unavailableCap).toContainText('No homes with identified protest activity have both 2026 preliminary and certified market values and a usable recorded preliminary cap.');await expect(unavailableMore.locator('..')).not.toContainText('0 / 0');
 await page.goto('/property/9204/neighborhood');await expect(page.locator('.neighborhood-story')).toContainText('Not available');await expect(page.locator('.neighborhood-results')).toContainText('Missing results are not zero reductions');await expect(page.locator('summary').filter({hasText:'About this analysis'}).locator('..')).toContainText('zero denominators are unavailable, not zero percent');await expect(page.locator('.neighborhood-page')).not.toContainText(/NaN|Infinity|96\.5%|at least 5%/);await expect(page.locator('.neighborhood-story')).not.toContainText('$0');
});
test('neighborhood responsive layout and zoom',async({page},info)=>{
 await page.goto('/property/9200/neighborhood');await expect(page.locator('.neighborhood-carry')).toBeVisible();await expect(page.locator('.neighborhood-carry')).toContainText('at least 10%');await page.evaluate(()=>document.fonts.ready);
 const agents=page.locator('.neighborhood-agent-activity'),agentPanels=agents.locator('.neighborhood-agent-panel');await expect(agentPanels).toHaveCount(2);await expect(agentPanels.nth(0)).toContainText('2026 certified appraisal');await expect(agentPanels.nth(0)).toContainText('certified values exported Jul 18, 2026');await expect(agentPanels.nth(1)).toContainText('2025 certified appraisal');await expect(agentPanels.nth(1)).toContainText('Other agents (1)');await expect(agents.getByRole('img').first()).toHaveAttribute('aria-label',/properties on a shared scale with a maximum of/);
 const more=page.locator('summary').filter({hasText:'More annual outcomes and comparisons'});await more.click();const expanded=more.locator('..'),cap=expanded.locator('.neighborhood-cap-progression');await expect(cap).toBeVisible();await expect(expanded.getByRole('region',{name:'2026 protest activity comparison'})).toBeVisible();await expect(expanded).toContainText(/2025: \d+ of \d+ paired homes reduced/);
 const width=info.project.use.viewport!.width;
 if(width===1440||width===375){if(width===375)await page.setViewportSize({width:390,height:1000});const path=info.outputPath(width===1440?'neighborhood-desktop.png':'neighborhood-mobile.png');await page.screenshot({path,fullPage:true});await info.attach('Neighborhood layout',{path,contentType:'image/png'});const capPath=info.outputPath(width===1440?'cap-progression-1440.png':'cap-progression-390.png');await cap.screenshot({path:capPath});await info.attach('Cap progression',{path:capPath,contentType:'image/png'});const agentPath=info.outputPath(width===1440?'agent-activity-1440.png':'agent-activity-390.png');await agents.screenshot({path:agentPath});await info.attach('Agent activity',{path:agentPath,contentType:'image/png'});}
 const stages=page.locator('.neighborhood-story-stage'),boxes=await stages.evaluateAll(nodes=>nodes.map(node=>{const b=node.getBoundingClientRect();return {x:b.x,y:b.y};}));
 if(width===1440){expect(boxes[0].y).toBe(boxes[1].y);expect(boxes[1].y).toBe(boxes[2].y);expect(boxes[0].x).toBeLessThan(boxes[1].x);expect(boxes[1].x).toBeLessThan(boxes[2].x);const panelBoxes=await agentPanels.evaluateAll(nodes=>nodes.map(node=>{const b=node.getBoundingClientRect();return {x:b.x,y:b.y};}));expect(panelBoxes[0].y).toBe(panelBoxes[1].y);expect(panelBoxes[0].x).toBeLessThan(panelBoxes[1].x);}else{expect(boxes[0].y).toBeLessThan(boxes[1].y);expect(boxes[1].y).toBeLessThan(boxes[2].y);}
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 if(width===375){await page.setViewportSize({width:320,height:1000});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);const path=info.outputPath('cap-progression-320.png');await cap.screenshot({path});await info.attach('Cap progression 320',{path,contentType:'image/png'});const agentPath=info.outputPath('agent-activity-320.png');await agents.screenshot({path:agentPath});await info.attach('Agent activity 320',{path:agentPath,contentType:'image/png'});}
 if(width===1440){await page.evaluate(()=>{document.documentElement.style.zoom='2';});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);const path=info.outputPath('cap-progression-200-percent.png');await cap.screenshot({path});await info.attach('Cap progression 200 percent',{path,contentType:'image/png'});const agentPath=info.outputPath('agent-activity-200-percent.png');await agents.screenshot({path:agentPath});await info.attach('Agent activity 200 percent',{path:agentPath,contentType:'image/png'});}
});
