import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
test('neighborhood outcomes, chart, release continuity and accessible layout',async({page},info)=>{
 await page.goto('/property/100');
 await page.getByRole('navigation',{name:'Property tools'}).getByRole('link',{name:'Neighborhood',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Your neighborhood',exact:true})).toBeVisible();
 await expect(page.getByText('Subdivision on record:')).toContainText('GRAND MESA SECTION II');
 await expect(page.getByRole('navigation',{name:'Property tools'}).locator('[aria-current="page"]')).toHaveText('Neighborhood');
 await expect(page.locator('.neighborhood-own-result')).toContainText('$50,000');
 await expect(page.locator('.neighborhood-outcomes')).toContainText('20.0%');
 await expect(page.locator('.neighborhood-outcomes')).toContainText('of 5 included homes');
 await expect(page.locator('.neighborhood-population')).toHaveCount(0);
 await expect(page.locator('.neighborhood-cap-definition')).toContainText('plus the value of qualifying new improvements');
 await expect(page.locator('.neighborhood-outcomes')).toContainText('Values reduced from preliminary');
 await expect(page.locator('.neighborhood-outcomes')).not.toContainText('1 ·');
 await expect(page.locator('.neighborhood-insight')).toContainText('where this comparison could be made');
 await expect(page.locator('.neighborhood-protest-strip')).toContainText('Median reduction');
 await page.getByRole('button',{name:'Value per sq. ft.',exact:true}).focus();await page.keyboard.press('Enter');
 await expect(page.getByRole('button',{name:'Value per sq. ft.',exact:true})).toHaveAttribute('aria-pressed','true');
 await expect(page.getByRole('img',{name:/Value per square foot distribution/})).toBeVisible();
 await page.getByText('View distribution counts',{exact:true}).click();
 await expect(page.locator('.neighborhood-chart-data')).toContainText('homes');
 await page.getByText('View distribution counts',{exact:true}).click();
 await page.getByRole('button',{name:'Market value',exact:true}).click();
 const capture=info.outputPath('neighborhood-page.png');await page.screenshot({path:capture,fullPage:true});await info.attach('Neighborhood page',{path:capture,contentType:'image/png'});
 expect((await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations).toEqual([]);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.evaluate(()=>{document.documentElement.style.fontSize='200%';});
 const overflow=await page.evaluate(()=>Array.from(document.querySelectorAll('main *')).filter(e=>e.getBoundingClientRect().right>innerWidth&&!e.closest('.neighborhood-table-scroll')).map(e=>({tag:e.tagName,class:e.className,text:e.textContent?.slice(0,60),right:e.getBoundingClientRect().right})));
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),JSON.stringify(overflow)).toBe(true);
 await page.evaluate(()=>{document.documentElement.style.fontSize='';window.scrollTo(0,0);});
 await expect(page.getByRole('link',{name:'Print or save PDF'})).toBeVisible();
 await page.getByRole('link',{name:'Print or save PDF'}).click();
 await page.waitForLoadState('networkidle');await expect(page).toHaveURL(/\/neighborhood\/print/);
 await expect(page.getByRole('heading',{name:'Appraisal data snapshot',exact:true})).toBeVisible();
 await expect(page.getByRole('button',{name:'Print or save as PDF'})).toBeVisible();
 await expect(page.locator('.print-sheet')).toHaveCount(2);
 await expect(page.locator('.print-page-two')).toContainText('Protest activity and reductions');
 await expect(page.locator('.print-page-two')).toContainText('Median reduction among reduced homes');
 await expect(page.locator('.print-page-two')).toContainText('PS-NBR-2026.1');
 await expect(page.locator('.print-page-two')).toContainText('Live analysis:');
 await page.emulateMedia({media:'print'});
 await expect(page.locator('.print-toolbar')).toBeHidden();
 expect(await page.evaluate(()=>Array.from(document.querySelectorAll('.print-sheet')).every(sheet=>Math.abs(sheet.getBoundingClientRect().height-1056)<2))).toBe(true);
 await page.emulateMedia({media:'screen'});await page.getByRole('link',{name:'Back to neighborhood analysis'}).click();
 await expect(page).toHaveURL(/\/property\/100\/neighborhood\?release=/);
 const snapshotSelect=page.locator('#neighborhood-release');
 await snapshotSelect.selectOption('33333333-3333-4333-8333-333333333333');await page.getByRole('button',{name:'View',exact:true}).click();
 await expect(page).toHaveURL(/release=33333333/);await expect(page.locator('.neighborhood-season-badge')).toContainText('Comparison incomplete');
 await expect(page.locator('.neighborhood-own-result')).toHaveCount(0);
 await page.reload();await expect(snapshotSelect).toHaveValue('33333333-3333-4333-8333-333333333333');
 await snapshotSelect.selectOption('22222222-2222-4222-8222-222222222222');await page.getByRole('button',{name:'View',exact:true}).click();
 await expect(page.locator('.neighborhood-season-badge')).toContainText('2025');
 await page.getByText('Compare homes with and without identified protest activity',{exact:true}).click();
 await expect(page.getByRole('row').filter({hasText:'Started above their recorded cap'})).toContainText('Not available');
 await page.goto('/property/103/neighborhood');await expect(page.getByRole('heading',{name:'Let’s try another address'})).toBeVisible();
});
