import { test, expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
test('brand, search, definitions and accessible responsive layout', async ({page}, info) => {
  await page.goto('/');
  await page.evaluate(() => document.fonts.ready);
  await expect(page.getByRole('img',{name:'ParcelSavvy',exact:true})).toBeVisible();
  await expect(page.getByRole('heading',{level:1})).toHaveText('What happened to your property appraisal?');
  await expect(page.getByRole('heading',{name:'Your records become a story you can use.'})).toBeVisible();
  await expect(page.getByRole('heading',{name:'Useful property information shouldn’t disappear behind a paywall.'})).toBeVisible();
  await expect(page.getByRole('button',{name:'Support ParcelSavvy'})).toBeDisabled();
  await expect(page.getByText('Optional contributions are not tax-deductible unless ParcelSavvy later becomes a qualified charitable organization.')).toBeVisible();
  expect(await page.locator('h1').evaluate(el=>getComputedStyle(el).fontFamily)).toMatch(/manrope/i);
  expect(await page.locator('body').evaluate(el=>getComputedStyle(el).fontFamily)).toMatch(/inter/i);
  await expect(page.getByRole('button',{name:'Search my property'})).toHaveCSS('background-color','rgb(23, 105, 170)');
  await page.getByLabel('Property address or TCAD property ID').fill('Oak');
  await page.getByRole('button',{name:'Search my property'}).click();
  await expect(page.locator('.result-card')).toHaveCount(2);
  const term=page.getByRole('button',{name:'TCAD market value'});
  await term.focus(); await expect(page.getByRole('tooltip')).toBeVisible();
  await term.press('Escape'); await expect(page.getByRole('tooltip')).toBeHidden();
  const issues=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();
  expect(issues.violations).toEqual([]);
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  const capture=info.outputPath('search-results.png');
  await page.screenshot({path:capture,fullPage:true});
  await info.attach('Responsive search results',{path:capture,contentType:'image/png'});
  if(process.env.BRAND_VISUAL_COMPARE==='1') await expect(page).toHaveScreenshot('search-results.png',{fullPage:true});
  await page.goto('/?q=Parkdemo');
  await expect(page.locator('.result-card')).toHaveCount(5);
  await page.getByLabel('Show all parcels',{exact:true}).check();
  await expect(page.locator('.result-card')).toHaveCount(20);
  await expect(page).toHaveURL(/all=1/);
  await page.goto('/?q=NoSuchStreet');
  await expect(page.getByRole('heading',{name:'No matching addresses found'})).toBeVisible();
});

test('address variants and labeled spelling suggestions', async ({page}, info) => {
  await page.goto('/?q=1800+West+36th+Street');
  await expect(page.locator('.result-card').first()).toContainText('1800 W 36 ST');
  await expect(page.locator('.result-card')).toHaveCount(3);
  await page.getByLabel('Property address or TCAD property ID').fill('700 Paw Prnit Drive Apt 2');
  await page.getByRole('button',{name:'Search my property'}).click();
  await expect(page.getByRole('heading',{name:'Possible matches',exact:true})).toBeVisible();
  await expect(page.locator('.result-card')).toHaveCount(1);
  await expect(page.locator('.result-card')).toContainText('700 PAW PRINT DR UNIT 2');
  expect((await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations).toEqual([]);
  await page.locator('.result-card').focus();
  const capture=info.outputPath('possible-matches.png');
  await page.screenshot({path:capture,fullPage:true});
  await info.attach('Possible matches',{path:capture,contentType:'image/png'});
  await page.evaluate(()=>{document.documentElement.style.fontSize='200%';});
  const overflowing = await page.evaluate(()=>Array.from(document.querySelectorAll('body *')).filter(el=>el.getBoundingClientRect().right>innerWidth+1).map(el=>({tag:el.tagName,className:el.className})));
  expect(overflowing).toEqual([]);
  const enlarged=info.outputPath('possible-matches-enlarged.png');
  await page.screenshot({path:enlarged,fullPage:true});
  await info.attach('Possible matches with enlarged text',{path:enlarged,contentType:'image/png'});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.locator('.result-card').press('Enter');
  await expect(page).toHaveURL(/property\/990010/);
});
