import { test, expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
test('brand, search, definitions and accessible responsive layout', async ({page}, info) => {
  await page.goto('/');
  await page.evaluate(() => document.fonts.ready);
  await expect(page.getByRole('img',{name:'ParcelSavvy',exact:true})).toBeVisible();
  await expect(page.getByRole('heading',{level:1})).toHaveText('Know your property.Understand your assessment.');
  expect(await page.locator('h1').evaluate(el=>getComputedStyle(el).fontFamily)).toMatch(/manrope/i);
  expect(await page.locator('body').evaluate(el=>getComputedStyle(el).fontFamily)).toMatch(/inter/i);
  await expect(page.getByRole('button',{name:'Search property'})).toHaveCSS('background-color','rgb(23, 105, 170)');
  await page.getByLabel('Property address or property ID').fill('Oak');
  await page.getByRole('button',{name:'Search property'}).click();
  await expect(page.locator('.result-card')).toHaveCount(2);
  const term=page.getByRole('button',{name:'TCAD market value'});
  await term.focus(); await expect(page.getByRole('tooltip')).toBeVisible();
  await term.press('Escape'); await expect(page.getByRole('tooltip')).toBeHidden();
  const issues=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();
  expect(issues.violations).toEqual([]);
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  const capture=info.outputPath('search-results.png');
  await page.screenshot({path:capture,fullPage:true});
  await info.attach('Responsive search results',{path:capture,contentType:'image/png'});
  if(process.env.BRAND_VISUAL_COMPARE==='1') await expect(page).toHaveScreenshot('search-results.png',{fullPage:true});
  await page.goto('/?q=Parkdemo');
  await expect(page.locator('.result-card')).toHaveCount(5);
  await page.getByLabel('Show all parcels',{exact:true}).check();
  await expect(page.locator('.result-card')).toHaveCount(20);
  await expect(page).toHaveURL(/all=1/);
  await page.goto('/?q=NoSuchStreet');
  await expect(page.getByRole('heading',{name:'No matching addresses found'})).toBeVisible();
});
