import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
test('admin access, saved drafts, phase previews and public isolation',async({page},info)=>{
 await page.goto('/admin');
 await expect(page).toHaveURL(/\/admin\/login/);
 await expect(page.getByRole('heading',{name:'Administrator sign-in'})).toBeVisible();
 expect((await new AxeBuilder({page}).analyze()).violations).toEqual([]);
 await page.getByLabel('Email',{exact:true}).fill('admin@example.test');
 await page.getByLabel('Password',{exact:true}).fill('fixture-password');
 await page.getByRole('button',{name:'Sign in',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Administration',exact:true})).toBeVisible();
 await expect(page.getByRole('heading',{name:'Season calendar',exact:true})).toBeVisible();
 // Use a distinct supported year for each viewport because the fixture server is shared.
 const testYear=info.project.name==='width-375'?2027:info.project.name==='width-768'?2028:2029;
 await page.getByLabel('Tax year',{exact:true}).fill(String(testYear));
 await page.getByLabel('Season start / override effective date').fill(`${testYear}-04-02`);
 await page.getByLabel('General filing deadline').fill(`${testYear}-05-15`);
 await page.getByLabel('Post-season starts').fill(`${testYear}-08-01`);
 await page.getByLabel('Deadline verified on').fill('2026-09-11');
 await page.getByLabel('Official deadline source').fill('https://traviscad.org/protests');
 await page.getByRole('button',{name:'Save draft',exact:true}).click();
 await expect(page.getByRole('status')).toContainText('Draft saved. Public guidance is unchanged.');
 await page.getByRole('button',{name:'Protest season',exact:true}).click();
 await expect(page.locator('#season-heading')).toHaveText('Follow the available records and prepare your evidence');
 await page.getByRole('button',{name:'Post-protest season',exact:true}).click();
 await expect(page.locator('#season-heading')).toHaveText('Review the result and what changed');
 expect((await new AxeBuilder({page}).analyze()).violations).toEqual([]);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.screenshot({path:info.outputPath('admin-season.png'),fullPage:true});
 await page.goto('/admin/preview?release=11111111-1111-4111-8111-111111111111&property=100&phase=preliminary');
 await expect(page.getByRole('heading',{name:'Property preview',exact:true})).toBeVisible();
 await expect(page.locator('#season-heading')).toContainText('Understand the proposed value');
 await page.getByLabel('Phase',{exact:true}).selectOption('protest');
 await page.getByRole('button',{name:'Update preview'}).click();
 await expect(page.locator('#season-heading')).toContainText('Follow the available records');
 await page.getByLabel('Phase',{exact:true}).selectOption('post');
 await page.getByRole('button',{name:'Update preview'}).click();
 await expect(page.locator('#season-heading')).toContainText('Review the result');
 await page.goto('/property/100');
 await expect(page.locator('#season-heading')).toHaveText('Review the result and what changed');
 await page.goto('/admin');
 await page.getByRole('button',{name:'Sign out',exact:true}).click();
 await expect(page).toHaveURL(/\/admin\/login/);
 await page.goto('/admin/preview?release=11111111-1111-4111-8111-111111111111&property=100');
 await expect(page).toHaveURL(/\/admin\/login/);
});
