import Link from 'next/link';
import {notFound} from 'next/navigation';
import {SiteHeader,SiteFooter} from '@/components/site-shell';
import {PropertyNavigation} from '@/components/property-navigation';
import {NeighborhoodDistribution} from '@/components/neighborhood-distribution';
import {getNeighborhood} from '@/lib/supabase/neighborhood';
import {neighborhoodSummary} from '@/lib/neighborhood';
import {validPropertyId} from '@/lib/property-comparisons';
import {dateLabel} from '@/lib/property-history';
import '../property-overview.css';
import '../compare/comparison.css';
import './neighborhood.css';
export const maxDuration=30;
export const metadata={title:'Your neighborhood | ParcelSavvy'};
const money=(n:number|null)=>n===null?'Not available':n.toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0});
const pct=(n:number|null)=>n===null?'Not available':`${n.toFixed(1)}%`;
const count=(n:number)=>n.toLocaleString('en-US');
const rate=(r:{count:number;total:number;percent:number|null})=>`${count(r.count)} of ${count(r.total)} · ${pct(r.percent)}`;
export default async function NeighborhoodPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<Record<string,string|string[]|undefined>>}) {
 const {id}=await params,search=await searchParams;if(!validPropertyId(id))notFound();
 const result=await getNeighborhood(id,typeof search.release==='string'?search.release:null);
 if(result.status==='missing_property')notFound();
 if(result.status!=='ok')return <><SiteHeader/><main id="main-content" className="main-shell profile-shell"><h1>Your neighborhood</h1><PropertyNavigation propertyId={id} active="neighborhood"/><div className="notice"><h2>{result.status==='missing_area'?'No market area is recorded for this property':result.status==='missing_snapshot'?'Neighborhood records are not available for this release':result.status==='area_too_large'?'This market area needs a larger analysis':result.status==='invalid'?'Check the neighborhood link':'Neighborhood data is temporarily unavailable'}</h2><p>Return to the latest records or open the property overview.</p><Link href={`/property/${id}/neighborhood`}>Latest neighborhood records</Link> · <Link href={`/property/${id}`}>Property overview</Link></div></main><SiteFooter/></>;
 const d=result.data,s=neighborhoodSummary(d),r=d.releases.find(r=>r.dataset_id===d.source_id)!;
 const pre=d.releases.find(r=>r.dataset_id===d.preliminary_id),cert=d.releases.find(r=>r.dataset_id===d.certified_id);
 const complete=!!pre&&!!cert,href=`/property/${id}/compare?release=${d.source_id}`;
 const rows:[string,string,string][]=[['Homes',count(s.protested.count),count(s.other.count)],['Initially above the cap',rate(s.protested.above),rate(s.other.above)],['Values reduced',complete?rate(s.protested.reduced):'Not available',complete?rate(s.other.reduced):'Not available'],['Moved below the cap',complete?rate(s.protested.crossed):'Not available',complete?rate(s.other.crossed):'Not available'],['Preliminary median value',money(s.protested.preliminaryMedian),money(s.other.preliminaryMedian)],['Certified median value',money(s.protested.certifiedMedian),money(s.other.certifiedMedian)],['Certified median per sq. ft.',money(s.protested.certifiedPerFoot),money(s.other.certifiedPerFoot)]];
 return <><SiteHeader/><main id="main-content" className="main-shell profile-shell neighborhood-page">
  <Link href={`/property/${id}`} className="back-link">← Back to property overview</Link>
  <div className="comparison-property-heading"><div><p className="eyebrow">TCAD PROPERTY {id}</p><h1>{d.subject.address}</h1><p>Your property · {d.subject.living_area?.toLocaleString('en-US')??'Unreported'} sq. ft. · Built {d.subject.year_built??'not reported'} · Class {d.subject.class_code??'not reported'}</p></div><div><p>Reported market value</p><strong className="neighborhood-property-value">{money(d.subject.market_value)}</strong></div></div>
  <PropertyNavigation propertyId={id} active="neighborhood"/>
  <div className="neighborhood-section-heading neighborhood-title"><div><h2>Your neighborhood</h2><p>TCAD market area <strong>{d.neighborhood}</strong> · Residential homes</p><p className="neighborhood-note">Market-area boundaries may differ from your subdivision.</p></div>
   <form className="neighborhood-release" action={`/property/${id}/neighborhood`}><label htmlFor="neighborhood-release">Assessment release</label><div><select name="release" id="neighborhood-release" defaultValue={d.source_id}>{d.releases.map(x=><option key={x.dataset_id} value={x.dataset_id}>{x.tax_year} {x.roll_stage} · {dateLabel(x.export_date)}</option>)}</select><button type="submit">View</button></div></form></div>
  <dl className="neighborhood-snapshot">
   <div><dt>Homes in this release</dt><dd>{count(s.all.count)}</dd></div>
   <div><dt>Median market value</dt><dd>{money(s.median)}</dd></div>
   <div><dt>Your home vs. median</dt><dd>{s.difference===null?'Not available':s.difference===0?'At the median':`${money(Math.abs(s.difference))} ${s.difference>0?'above':'below'}`}</dd><span>{s.differencePercent===null?'':`${pct(Math.abs(s.differencePercent))} ${s.differencePercent>=0?'higher':'lower'}`}</span></div>
   <div><dt>Median value per sq. ft.</dt><dd>{money(s.medianPerFoot)}</dd><span>Market assessment, including land</span></div>
  </dl>
  {s.annual&&<p className="neighborhood-note">{pct(Math.abs(s.annual.percent))} {s.annual.percent>=0?'higher':'lower'} median market value than {r.tax_year-1} certified, using the same {count(s.annual.count)} homes in both releases.</p>}
  {!s.subjectIncluded&&<p className="notice">Your property is outside the residential-home population used for these neighborhood metrics.</p>}
  <NeighborhoodDistribution market={s.marketDistribution} area={s.areaDistribution} compareHref={href}/>
  <section className="neighborhood-panel" aria-labelledby="season-heading"><div className="neighborhood-section-heading"><h2 id="season-heading">From proposed values to {complete?'certified results':'available records'}</h2><span className="neighborhood-season-badge">{r.tax_year} · {complete?'Certified results':'Comparison incomplete'}</span></div>
   <p>How TCAD started, what changed, and which reductions went below the cap.</p>
   <p className="neighborhood-note">{pre?`${dateLabel(pre.export_date)} preliminary`:'Preliminary release not available'} → {cert?`${dateLabel(cert.export_date)} certified`:'Certified comparison not available for this release'}</p>
   <div className="neighborhood-outcomes">
    <article><h3>1 · Initially above the cap</h3><strong>{pre?`${count(s.all.above.count)} homes`:'Not available'}</strong><b>{pre?pct(s.all.above.percent):'—'}</b><p>of {count(s.all.above.total)} homes with a verified applicable cap and preliminary value</p><p className="neighborhood-outcome-explanation">Proposed market value exceeded the capped assessment.</p></article>
    <article><h3>2 · Values reduced</h3><strong>{complete?`${count(s.all.reduced.count)} homes`:'Not available'}</strong><b>{complete?pct(s.all.reduced.percent):'—'}</b><p>of {count(s.all.reduced.total)} homes with both values</p><p className="neighborhood-outcome-explanation">Market value decreased between preliminary and certified records.</p></article>
    <article className="neighborhood-cap-outcome"><h3>3 · Moved below the cap</h3><strong>{complete?`${count(s.all.crossed.count)} homes`:'Not available'}</strong><b>{complete?pct(s.all.crossed.percent):'—'}</b><p>of {count(s.all.crossed.total)} reduced homes that started at or above an identifiable cap threshold</p><p className="neighborhood-outcome-explanation">Final market value went below the protection already provided by the preliminary cap.</p></article>
   </div>
   {s.own&&<div className="neighborhood-own-result"><p><strong>Your home moved below the cap</strong></p><h3>{money(s.own.dollars)} below your preliminary capped assessment · {pct(s.own.percent)}</h3><p>From {money(s.own.threshold)} capped to {money(s.own.final)} certified. Value reduction before exemptions, not tax-dollar savings.</p></div>}
   <div className="neighborhood-protest-strip"><p>Protests on record: <strong>{count(s.protested.count)} of {count(s.all.count)} homes · {pct(s.participation)}</strong></p><p>Average reduction: <strong>{complete?`${money(s.all.averageReduction)} · ${pct(s.all.averagePercent)}`:'Not available'}</strong><span>among {count(s.all.reduced.count)} homes with reductions</span></p></div>
   <details className="neighborhood-details" open><summary>How recorded protests fit into the picture</summary><div className="neighborhood-table-scroll" role="region" aria-label="Neighborhood protest comparison" tabIndex={0}><table><thead><tr><th scope="col">Measure</th><th scope="col">Protest on record</th><th scope="col">No protest found</th></tr></thead><tbody>{rows.map(([label,a,b])=><tr key={label}><th scope="row">{label}</th><td>{a}</td><td>{b}</td></tr>)}</tbody></table></div><p className="neighborhood-note">Percentages use eligible homes in each group. Median comparisons use the same homes with both values. Protest records cover the tax year across all available imports, including records later than the selected valuation release.</p><p className="neighborhood-note">No protest found means none in available records. Groups may differ; observed reductions cannot all be attributed to protests.</p></details>
   <details className="neighborhood-details"><summary>Comparison coverage and other outcomes</summary><p>{count(s.all.unchanged)} unchanged · {count(s.all.increased)} increased · {count(s.all.missingPair)} without a complete usable value pair.</p><p>{count(s.all.capNotApplicable)} without an applicable homestead cap in the source · {count(s.all.capUnknown)} with unverified cap status.</p><p>{count(s.all.remainedAbove)} reduced homes remained at or above the identifiable cap. {count(s.all.reducedWithoutThreshold)} other reduced homes lack a binding preliminary cap threshold; this includes homes already below the cap and homes without an applicable cap.</p></details>
  </section>
  <section className="neighborhood-panel" aria-labelledby="entities-heading"><h2 id="entities-heading">Taxing authorities</h2><p className="neighborhood-note">Coverage can vary within a market area. Authorities applying to your property appear first.</p><details className="neighborhood-details" open><summary>View taxing authorities</summary><div className="neighborhood-table-scroll" role="region" aria-label="Neighborhood taxing authorities" tabIndex={0}><table><thead><tr><th scope="col">Authority</th><th scope="col">Homes covered</th><th scope="col">Your property</th></tr></thead><tbody>{s.entities.map(e=><tr key={e.code}><th scope="row">{e.name} <span className="neighborhood-note">({e.code})</span></th><td>{count(e.count)}</td><td>{e.applies?'Applies':'Not recorded'}</td></tr>)}</tbody></table></div>{!s.entities.length&&<p>No taxing authorities are recorded in this release.</p>}<p className="neighborhood-note">Authority records available for {count(s.entityCoverage)} of {count(s.all.count)} homes.</p></details></section>
  <details className="neighborhood-panel neighborhood-about"><summary>About these numbers</summary><p>Source: TCAD, {r.tax_year} {r.roll_stage}, {dateLabel(r.export_date)}. “Neighborhood” means the selected property’s TCAD market area. Homes have residential R1–R6 floor records in this release; vacant land and non-residential parcels are excluded. Only published, non-confidential records eligible for the site are represented.</p><p>The neighborhood median includes your home when it is in that population. Market-value calculations use {count(s.valueCount)} homes; value per square foot uses {count(s.areaCount)} with a reported living area. Missing values and anomalous market values below $1,000 are excluded from value calculations, but not the home count.</p><p>Per-square-foot values divide each home’s market value, including land, by its recorded primary-building living area. The displayed median is the median of those individual ratios. Percentile means the share with a strictly lower value; ties are not counted as lower.</p><p>Cap applicability uses TCAD’s homestead flag, qualification year, cap-loss amount, and reconciled market/appraised/assessed fields. A positive cap loss identifies a binding preliminary threshold. When cap loss is zero, the unused threshold cannot be recovered from these fields; those homes remain in the initial-applicability count when eligibility is verified, but are not assigned an invented threshold. Final values equal to the threshold do not count as below it.</p><p>Changes are measured against the preliminary cap recorded in the same tax year. Changes in eligibility, property characteristics, exemptions, rates, or tax ceilings can affect the eventual tax bill. These measures describe assessment outcomes.</p><p>Average dollar and percentage reductions include only homes whose market value fell. Percentage reductions are calculated per home before averaging. Each property is counted once for a protest flag or ARB case; an agent listing alone does not establish a protest.</p><p><a href="https://comptroller.texas.gov/taxes/property-tax/valuing-property.php" target="_blank" rel="noreferrer">Texas Comptroller: property valuation and appraisal limitations</a> · <a href="https://traviscad.org/" target="_blank" rel="noreferrer">Travis Central Appraisal District</a></p></details>
 </main><SiteFooter/></>;
}
