import Link from 'next/link';
import {notFound} from 'next/navigation';
import {SiteHeader,SiteFooter} from '@/components/site-shell';
import {PropertyNavigation} from '@/components/property-navigation';
import {NeighborhoodDistribution} from '@/components/neighborhood-distribution';
import {getNeighborhood} from '@/lib/supabase/neighborhood';
import {neighborhoodSummary} from '@/lib/neighborhood';
import {validPropertyId} from '@/lib/property-comparisons';
import {dateLabel} from '@/lib/property-history';
import '../property-overview.css';
import '../compare/comparison.css';
import './neighborhood.css';
export const maxDuration=30;
export const metadata={title:'Your neighborhood | ParcelSavvy'};
const money=(n:number|null)=>n===null?'Not available':n.toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0});
const homes=(n:number)=>`${n.toLocaleString('en-US')} ${n===1?'home':'homes'}`;
const pct=(n:number|null)=>n===null?'Not available':`${n.toFixed(1)}%`;
const count=(n:number)=>n.toLocaleString('en-US');
const rate=(r:{count:number;total:number;percent:number|null})=>`${count(r.count)} of ${count(r.total)} · ${pct(r.percent)}`;
export default async function NeighborhoodPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<Record<string,string|string[]|undefined>>}) {
 const {id}=await params,search=await searchParams;if(!validPropertyId(id))notFound();
 const result=await getNeighborhood(id,typeof search.release==='string'?search.release:null);
 if(result.status==='missing_property')notFound();
 if(result.status!=='ok')return <><SiteHeader/><main id="main-content" className="main-shell profile-shell"><h1>Your neighborhood</h1><PropertyNavigation propertyId={id} active="neighborhood"/><div className="notice"><h2>{result.status==='missing_area'?'No market area is recorded for this property':result.status==='missing_snapshot'?'Neighborhood records are not available for this release':result.status==='area_too_large'?'This market area needs a larger analysis':result.status==='invalid'?'Check the neighborhood link':'Neighborhood data is temporarily unavailable'}</h2><p>Return to the latest records or open the property overview.</p><Link href={`/property/${id}/neighborhood`}>Latest neighborhood records</Link> · <Link href={`/property/${id}`}>Property overview</Link></div></main><SiteFooter/></>;
 const d=result.data,s=neighborhoodSummary(d),r=d.releases.find(r=>r.dataset_id===d.source_id)!;
 const pre=d.releases.find(r=>r.dataset_id===d.preliminary_id),cert=d.releases.find(r=>r.dataset_id===d.certified_id);
 const complete=!!pre&&!!cert,href=`/property/${id}/compare?release=${d.source_id}`,printHref=`/property/${id}/neighborhood/print?release=${d.source_id}`;
 const rows:[string,string,string][]=[['Homes',count(s.protested.count),count(s.other.count)],['Started above their recorded cap',pre?rate(s.protested.shares.above):'Not available',pre?rate(s.other.shares.above):'Not available'],['Values reduced from preliminary',complete?rate(s.protested.shares.reduced):'Not available',complete?rate(s.other.shares.reduced):'Not available'],['Reduced below their recorded cap',complete?rate(s.protested.shares.crossed):'Not available',complete?rate(s.other.shares.crossed):'Not available'],['Preliminary median value',money(s.protested.preliminaryMedian),money(s.other.preliminaryMedian)],['Certified median value',money(s.protested.certifiedMedian),money(s.other.certifiedMedian)],['Certified median per sq. ft.',money(s.protested.certifiedPerFoot),money(s.other.certifiedPerFoot)]];
 return <><SiteHeader/><main id="main-content" className="main-shell profile-shell neighborhood-page">
  <Link href={`/property/${id}`} className="back-link">← Back to property overview</Link>
  <div className="comparison-property-heading"><div><p className="eyebrow">APPRAISAL DISTRICT PROPERTY {id}</p><h1>{d.subject.address}</h1><p>Your property · {d.subject.living_area?.toLocaleString('en-US')??'Unreported'} sq. ft. · Built {d.subject.year_built??'not reported'} · Class {d.subject.class_code??'not reported'}</p></div><div><p>Reported market value</p><strong className="neighborhood-property-value">{money(d.subject.market_value)}</strong></div></div>
  <PropertyNavigation propertyId={id} active="neighborhood"/>
  <div className="neighborhood-section-heading neighborhood-title"><div><h2>Your neighborhood</h2>{d.subdivision&&<p>Subdivision on record: <strong>{d.subdivision}</strong></p>}<p>Appraisal District market area <strong>{d.neighborhood}</strong> · Single-family residential properties</p><p className="neighborhood-note">Market-area boundaries may differ from subdivision boundaries.</p></div>
   <form className="neighborhood-release" action={`/property/${id}/neighborhood`}><label htmlFor="neighborhood-release">Appraisal data snapshot</label><div><select name="release" id="neighborhood-release" defaultValue={d.source_id}>{d.releases.map(x=><option key={x.dataset_id} value={x.dataset_id}>{x.tax_year} {x.roll_stage} · {dateLabel(x.export_date)}</option>)}</select><button type="submit">View</button></div></form></div>
  <dl className="neighborhood-snapshot">
   <div><dt>Homes included</dt><dd>{count(s.all.count)}</dd></div>
   <div><dt>Median market value</dt><dd>{money(s.median)}</dd></div>
   <div><dt>Your home vs. median</dt><dd>{s.difference===null?'Not available':s.difference===0?'At the median':`${money(Math.abs(s.difference))} ${s.difference>0?'above':'below'}`}<span>{s.differencePercent===null?'':s.differencePercent===0?'Same as median':`${pct(Math.abs(s.differencePercent))} ${s.differencePercent>=0?'higher':'lower'}`}</span></dd></div>
   <div><dt>Median value per sq. ft.</dt><dd>{money(s.medianPerFoot)}<span>Market assessment, including land</span></dd></div>
  </dl>
  {s.annual&&<p className="neighborhood-note">{pct(Math.abs(s.annual.percent))} {s.annual.percent>=0?'higher':'lower'} median market value than {r.tax_year-1} certified, using the same {count(s.annual.count)} homes in both releases.</p>}
  {!s.subjectIncluded&&<p className="notice">Your property is outside the residential-home population used for these neighborhood metrics.</p>}
  <NeighborhoodDistribution market={s.marketDistribution} area={s.areaDistribution} compareHref={href}/>
  <section className="neighborhood-panel" aria-labelledby="season-heading"><div className="neighborhood-section-heading"><h2 id="season-heading">From preliminary values to {complete?'certified results':'available records'}</h2><span className="neighborhood-season-badge">{r.tax_year} · {complete?'Certified results':'Comparison incomplete'}</span></div>
   <p>How preliminary appraisal values changed before certification.</p><p><strong>Each headline percentage uses the same {count(s.all.count)} included homes.</strong></p>
   <div className="neighborhood-cap-definition"><h3>What does “the cap” mean?</h3><p>For an eligible homestead, the appraisal cap generally limits the appraised value to last year’s appraised value plus 10%, plus the value of qualifying new improvements. These results use the capped amount recorded in the preliminary Appraisal District data.</p></div>
   <p className="neighborhood-note">{pre?`${dateLabel(pre.export_date)} preliminary`:'Preliminary release not available'} → {cert?`${dateLabel(cert.export_date)} certified`:'Certified comparison not available for this release'}</p>
   <div className="neighborhood-outcomes">
    <article><h3>Started above their recorded cap</h3><strong>{pre?homes(s.all.above.count):'Not available'}</strong><b>{pre?pct(s.all.shares.above.percent):'—'}</b><p>of {count(s.all.count)} included homes</p><p className="neighborhood-outcome-explanation">Preliminary market value was higher than the capped amount recorded for the home.</p></article>
    <article><h3>Values reduced from preliminary</h3><strong>{complete?homes(s.all.reduced.count):'Not available'}</strong><b>{complete?pct(s.all.shares.reduced.percent):'—'}</b><p>of {count(s.all.count)} included homes</p><p className="neighborhood-outcome-explanation">Market value decreased between preliminary and certified records.</p></article>
    <article className="neighborhood-cap-outcome"><h3>Reduced below their recorded cap</h3><strong>{complete?homes(s.all.crossed.count):'Not available'}</strong><b>{complete?pct(s.all.shares.crossed.percent):'—'}</b><p>of {count(s.all.count)} included homes</p><p className="neighborhood-outcome-explanation">Certified market value ended below the capped amount recorded in the preliminary data.</p></article>
   </div>
   <p className="neighborhood-note">Cap results include only homes where the available records identify an applicable cap and support the comparison. {count(s.all.capUnknown)} homes have unresolved cap information{complete?`; ${count(s.all.missingPair)} lack a usable value pair`:""}.</p>
   {s.own&&<div className="neighborhood-own-result"><p><strong>Your home was reduced below its recorded cap</strong></p><h3>{money(s.own.dollars)} below the preliminary capped amount · {pct(s.own.percent)}</h3><p>From {money(s.own.threshold)} capped to {money(s.own.final)} certified. This is an appraisal result before exemptions, not tax-dollar savings.</p></div>}
   {complete&&s.all.crossed.total>0&&<div className="neighborhood-insight"><h3>What this means</h3><p><strong>{homes(s.all.crossed.count)}</strong> were reduced from above their recorded cap to below it. That is <strong>{pct(s.all.crossed.percent)}</strong> of the {homes(s.all.crossed.total)} where this comparison could be made. For those homes, the reduction lowered the value used before exemptions below the cap that was already limiting it.</p></div>}
   <div className="neighborhood-protest-strip"><p>Homes with protest activity identified: <strong>{count(s.protested.count)} of {count(s.all.count)} homes · {pct(s.participation)}</strong></p><p>Average reduction: <strong>{complete?`${money(s.all.averageReduction)} · ${pct(s.all.averagePercent)}`:'Not available'}</strong><span>among {count(s.all.reduced.count)} homes with reductions</span></p></div>
   <details className="neighborhood-details"><summary>Compare homes with and without identified protest activity</summary><div className="neighborhood-table-scroll" role="region" aria-label="Neighborhood protest comparison" tabIndex={0}><table><thead><tr><th scope="col">Measure</th><th scope="col">Protest activity identified</th><th scope="col">No protest activity found</th></tr></thead><tbody>{rows.map(([label,a,b])=><tr key={label}><th scope="row">{label}</th><td>{a}</td><td>{b}</td></tr>)}</tbody></table></div><p className="neighborhood-note">Every percentage in a column uses all homes in that column. Protest activity reflects all available public records for the tax year, including observations later than the selected valuation snapshot.</p><p className="neighborhood-note">No protest activity found means none appears in the available records. A reduction cannot always be attributed to a protest.</p></details>
  </section>
  <section className="neighborhood-panel" aria-labelledby="entities-heading"><h2 id="entities-heading">Taxing authorities</h2><p className="neighborhood-note">Coverage can vary within a market area. Authorities applying to your property appear first.</p><details className="neighborhood-details" open><summary>View taxing authorities</summary><div className="neighborhood-table-scroll" role="region" aria-label="Neighborhood taxing authorities" tabIndex={0}><table><thead><tr><th scope="col">Authority</th><th scope="col">Homes covered</th><th scope="col">Your property</th></tr></thead><tbody>{s.entities.map(e=><tr key={e.code}><th scope="row">{e.name} <span className="neighborhood-note">({e.code})</span></th><td>{count(e.count)}</td><td>{e.applies?'Applies':'Not recorded'}</td></tr>)}</tbody></table></div>{!s.entities.length&&<p>No taxing authorities are recorded in this release.</p>}<p className="neighborhood-note">Authority records available for {count(s.entityCoverage)} of {count(s.all.count)} homes.</p></details></section>
  <div className="neighborhood-report-action"><div><h2>Take this neighborhood analysis with you</h2><p>Open a clean two-page report you can print or save as a PDF.</p></div><Link href={printHref} target="_blank" rel="noreferrer" className="neighborhood-report-link">Open printable report</Link></div>
  <details className="neighborhood-panel neighborhood-about"><summary>About this analysis</summary><p>Source: Travis Central Appraisal District, {r.tax_year} {r.roll_stage} release dated {dateLabel(r.export_date)}. This analysis includes {count(s.all.count)} properties classified as single-family residential in Appraisal District market area {d.neighborhood} with usable building and market-value data. Market-area boundaries may differ from subdivision boundaries. Market values include land.</p><p>Cap comparisons appear only where the public records identify an applicable homestead cap and support a preliminary-to-certified comparison. Eligibility changes and qualifying new improvements can affect the cap. Protest activity reflects the combined public records available for the tax year and may be incomplete. These are appraisal outcomes before exemptions, not estimates of tax savings.</p><p><a href="https://comptroller.texas.gov/taxes/property-tax/valuing-property.php" target="_blank" rel="noreferrer">Texas Comptroller: property valuation and appraisal limitations</a> · <a href="https://traviscad.org/" target="_blank" rel="noreferrer">Travis Central Appraisal District</a></p></details>
 </main><SiteFooter/></>;
}
