"""Rebuild the average-condition lookup from TCAD pricing PDFs (requires PyMuPDF).
Usage: python tools/extract-depreciation.py /path/to/pricing-pdfs
The inputs must be named 2025_Pricing_Schedules.pdf and 2026_Pricing_Schedules.pdf.
"""
import hashlib
import json
from pathlib import Path
import re
import sys
import fitz

output = {}
for year in (2025, 2026):
    path = Path(sys.argv[1]) / f'{year}_Pricing_Schedules.pdf'
    pages = [page.get_text() for page in fitz.open(path)]
    associations = {}
    for page, text in enumerate(pages, 1):
        for m in re.finditer(r'Residential Depreciation Association\n(R[1-6])\nImprovement-Depreciation\n(\d+)', text):
            assert m[1] not in associations
            associations[m[1]] = (m[2], page)
    assert len(associations) == 6
    classes = {}
    for cls, (pricing_id, association_page) in sorted(associations.items()):
        rows = []
        source_pages = set()
        pattern = rf'{year}\nImprovement-Depreciation\n{pricing_id}\n[^\n]+\nA\n(\d+)\n([\d.]+)'
        for page, text in enumerate(pages, 1):
            for m in re.finditer(pattern, text):
                rows.append([int(m[1]), float(m[2])])
                source_pages.add(page)
        rows.sort()
        assert rows and rows[0] == [0, 100]
        assert len({age for age, _ in rows}) == len(rows)
        assert rows[-1][0] == 999 and all(rows[i][0] == i for i in range(len(rows)-1))
        assert all(0 < good <= 100 for _, good in rows)
        classes[cls] = dict(pricingId=pricing_id, associationPage=association_page, pages=sorted(source_pages), rows=rows)
    output[str(year)] = dict(file=path.name, sha256=hashlib.sha256(path.read_bytes()).hexdigest(), classes=classes)
Path('web/src/lib/tcad-depreciation.ts').write_text(
    '// Generated by tools/extract-depreciation.py. Condition A (average), not Grade Factor A.\n'
    'export const depreciationSchedules: Record<string, {file:string;sha256:string;classes:Record<string, {pricingId:string;associationPage:number;pages:number[];rows:number[][]}>}> = '
    + json.dumps(output, separators=(',', ':')) + ';\n')
print('Extracted', sum(len(c['rows']) for y in output.values() for c in y['classes'].values()), 'class/age rows across two release years')
