import {adjustmentReasons,adjustmentSummary,type MarketAdjustment} from '@/lib/market-adjustments';
import './market-adjustment-panel.css';
const money=(n:number|null)=>n===null?'Not available':`${n>0?'+':n<0?'−':''}${Math.abs(n).toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0})}`;
const multiplier=(n:number)=>`${n.toLocaleString('en-US',{maximumFractionDigits:4})}×`;
const effectSentence=(effect:number|null|undefined,year:number)=>effect==null?'A supported cost estimate and both annual factors are needed to estimate the factor’s dollar effect.':effect===0?`Using the ${year} supported cost estimate, the factor change has an estimated $0 effect on modeled market value compared with keeping the previous year’s factor.`:`Using the ${year} supported cost estimate, the factor change ${effect>0?'adds':'subtracts'} approximately ${Math.abs(effect).toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0})} ${effect>0?'to':'from'} modeled market value compared with keeping the previous year’s factor.`;
export function MarketAdjustmentPanel({data,propertyId,neighborhood=false}:{data:MarketAdjustment|null;propertyId:string;neighborhood?:boolean}) {
  if(!data)return <section className="market-adjustment-panel" id="market-adjustment" aria-labelledby="market-adjustment-heading"><h2 id="market-adjustment-heading" tabIndex={-1}>Neighborhood market adjustment</h2><p>Market-adjustment data is not available for this property right now.</p></section>;
  const s=adjustmentSummary(data),home=data.homes.find(h=>h.property_id===propertyId);
  return <section className="market-adjustment-panel" id="market-adjustment" aria-labelledby="market-adjustment-heading">
    <p className="eyebrow">{data.year} · MARKET AREA {data.neighborhood}</p>
    <h2 id="market-adjustment-heading" tabIndex={-1}>Neighborhood market adjustment</h2>
    <p><strong>Your home’s appraisal depends partly on where it is.</strong></p>
    <p>The district estimates the cost of rebuilding your home and features such as garages and pools, then reduces that estimate for age and condition. This is the starting cost estimate before the neighborhood factor is applied. Land is valued separately.</p>
    <p>That neighborhood adjustment is expressed as a multiplier. For example, if the starting estimate is <strong>$200,000</strong>, a multiplier of <strong>1.50</strong> raises it to <strong>$300,000</strong>.</p>
    <p><strong>When the multiplier goes up, your appraisal can increase even if nothing about your home has changed.</strong> The Appraisal District applies the factor to its estimated rebuilding cost after accounting for age and condition. ParcelSavvy estimates how changing that factor affects your home’s modeled value, keeping the other inputs the same.</p>
    <dl className="market-adjustment-metrics">
      <div><dt>Change in multiplier</dt><dd>{s.previous&&s.current?`${multiplier(s.previous.factor)} → ${multiplier(s.current.factor)}`:'Not available'}</dd><dd className="market-adjustment-note">{s.percent===null?'Both annual schedules are needed.':`${s.percent>0?'+':''}${s.percent.toFixed(1)}% from ${data.year-1} to ${data.year}`}</dd></div>
      {neighborhood&&<div><dt>Median estimated effect across matched homes</dt><dd>{money(s.median)}</dd><dd className="market-adjustment-note">{s.count.toLocaleString()} of {s.total.toLocaleString()} included homes qualify for this estimate.</dd></div>}
      <div><dt>Estimated change caused by the neighborhood adjustment</dt><dd>{money(home?.effect??null)}</dd><dd className="market-adjustment-note">{home?.effect!=null?'Changing only the neighborhood multiplier, with current-year preliminary inputs held fixed.':home?adjustmentReasons[home.status]:'Your home is outside the included population.'}</dd></div>
      {!neighborhood&&<div><dt>Actual preliminary change in home &amp; other features</dt><dd>{money(home?.actual_change??null)}</dd><dd className="market-adjustment-note">{home?.actual_change!=null?`${data.year-1} preliminary → ${data.year} preliminary`:'Original preliminary values for the home and other features in the same neighborhood are needed for both years. Later records that may include protest changes are excluded.'}</dd></div>}
    </dl>
    <p className="market-adjustment-note">{effectSentence(home?.effect,data.year)} Land and other input changes are separate; this isolates the factor’s contribution and is not necessarily the total annual change or tax savings.</p>
    <h3>Multiplier history</h3>
    {data.history.length?<div className="market-adjustment-history" role="region" aria-label="Neighborhood multiplier history" tabIndex={0}><table><thead><tr><th scope="col">Year</th><th scope="col">Multiplier</th><th scope="col">District source</th></tr></thead><tbody>{data.history.map(h=><tr key={h.year}><th scope="row">{h.year}</th><td>{multiplier(h.factor)}</td><td><a href={`/data/tcad/${h.filename}#page=${h.page}`}>{h.year} schedule, p. {h.page}</a></td></tr>)}</tbody></table></div>:<p>No schedule has been matched to this exact market-area code.</p>}
    <details><summary>How this estimate works and what is covered</summary>
      <p>We compare the first eligible dated preliminary record for this tax year with the same model using the previous year’s multiplier. All other current-year inputs stay fixed. The estimate is the difference between those two rounded model values. We include a home only when its rebuilding-cost components and current multiplier reproduce the Appraisal District’s recorded preliminary value of the home and other features within $1 and one residential building is verified.</p>
      <p>Matched homes must have a residential building in the prior-year records and appear under the same market-area code in both years. Neighborhood codes are matched exactly; renamed areas and boundary changes have not been crosswalked. History starts with the available 2025 and 2026 schedules. A missing year is not treated as an unchanged multiplier.</p>
      {neighborhood&&<><p>The median uses each qualifying home’s individual dollar estimate, including decreases and zero changes. It describes the matched homes shown in the count; it is not a countywide or whole-neighborhood total.</p>{s.excluded.length>0&&<ul>{s.excluded.map(x=><li key={x.reason}>{x.count.toLocaleString()} {x.count===1?'home':'homes'}: {x.label.toLowerCase()}</li>)}</ul>}</>}
      {home?.preliminary_date&&<p>Your preliminary record: {home.preliminary_date}{home.prior_preliminary_date?`; prior preliminary: ${home.prior_preliminary_date}`:''}.</p>}
      <p>This estimates the effect on the modeled value of the home and other features. It is not a change in land value, a tax bill, or potential tax savings. Rebuilding costs, depreciation, property details and overrides can also change the recorded value. The estimated effect can exceed the net annual increase when other changes offset it.</p>
      <p>Source files: {data.history.map(h=>h.filename).join(", ")||"No exact-code match"}.</p>
      <p>Sources: Appraisal District annual market-adjustment schedules identified above and the published property records. <a href="/data/tcad/2026_Residential_Valuation_Manual.pdf#page=8">Appraisal District’s 2026 residential valuation manual, p. 8</a> describes the sales comparison used to set these adjustments; this analysis does not reconstruct the district’s selected sales or prove an appraisal is incorrect.</p>
    </details>
  </section>;
}
