import {type neighborhoodAnalysis,type NeighborhoodAnalysisData} from '@/lib/neighborhood-analysis';
import {adjustmentSummary} from '@/lib/market-adjustments';
import {dateLabel} from '@/lib/property-history';
import {currency} from '@/lib/property-search';
import {NeighborhoodStory} from './neighborhood-analysis-view';
type Analysis=ReturnType<typeof neighborhoodAnalysis>;
const money=(n:number|null|undefined)=>n==null?'Unavailable':currency(n);
const pct=(n:number|null|undefined)=>n==null?'Unavailable':`${n>0?'+':''}${n.toFixed(1)}%`;
const ratio=(s:{count:number;total:number})=>s.total?`${s.count} / ${s.total}`:'Unavailable';
export function NeighborhoodReport({data:d,analysis:a}:{data:NeighborhoodAnalysisData;analysis:Analysis}) {
 const s=a.currentSummary,r=a.current,o=a.latestOutcome;
 const m=d.market_adjustment?adjustmentSummary(d.market_adjustment):null;
 const distribution=s.marketDistribution,bins=distribution.bins.flatMap((b,i,all)=>i%2?[]:[{low:b.low,high:all[i+1]?.high??b.high,count:b.count+(all[i+1]?.count??0)}]),peak=Math.max(1,...bins.map(b=>b.count));
  return <div className="neighborhood-report-content">
  <section className="nbr-summary" aria-label="Current neighborhood position">
   <NeighborhoodStory analysis={a} print/>
   <table className="nbr-table nbr-position"><colgroup><col style={{width:'34%'}}/><col style={{width:'22%'}}/><col style={{width:'22%'}}/><col style={{width:'22%'}}/></colgroup><caption><h2>Where your home sits</h2><p>Same-period values: {r.tax_year} {r.roll_stage} · {dateLabel(r.export_date)}. This group is not a matched comparable set.</p></caption><thead><tr><th>Measure</th><th>Your home</th><th>Group median</th><th>Difference</th></tr></thead><tbody>{[["Market value",s.marketDistribution],["Market value / living sq ft",s.areaDistribution]].map(([name,v])=>{const x=v as typeof distribution;return <tr key={String(name)}><th scope="row">{String(name)}<small>{x.count} eligible homes</small></th><td>{money(x.subject)}</td><td>{money(x.median)}</td><td>{x.subject!==null&&x.median!==null&&x.median>0?pct((x.subject/x.median-1)*100):'Unavailable'}</td></tr>;})}</tbody></table>
   {bins.length?<figure className="nbr-chart"><figcaption>Market-value distribution · {distribution.count} homes</figcaption><ul className="sr-only" aria-label="Market-value ranges">{bins.map((b,i)=><li key={i}>{money(b.low)} to {money(b.high)}{i===bins.length-1?", inclusive":", upper boundary excluded"}: {b.count} homes</li>)}</ul><div className="nbr-bars" aria-hidden="true">{bins.map((b,i)=><div key={i}><span>{b.count}</span><i style={{height:`${b.count/peak*78}px`}}/></div>)}</div><div className="nbr-range"><span>{money(distribution.min)}</span><span>Market value, including land</span><span>{money(distribution.max)}</span></div><p>Adjacent equal-width bins are combined; the last includes its upper boundary. Differences can reflect size, land, condition and features.</p></figure>:<p>No usable distribution is available. Missing values are not zero.</p>}
   <div className="nbr-outcome"><h2>{o?`What changed during ${o.certified.tax_year}`:'Annual outcomes'}</h2>{o?<><p><strong>{money(o.all.medianReduction)} median reduction · {o.all.medianPercent===null?'Unavailable':`${o.all.medianPercent.toFixed(1)}%`} median individual reduction</strong><br/>Among {o.all.reduced.count} homes reduced from proposed to certified value.</p><p>{o.all.crossed.total?`${ratio(o.all.crossed)} reduced homes that started at or above a usable recorded cap ended below it.`:'A usable recorded-cap comparison is unavailable.'} Cap and reduction denominators differ.</p><p>{ratio(o.participation)} homes have identified protest activity, including recorded protests and inferred reductions. This does not establish causation. {o.all.missingPair} homes lack paired values.</p></>:<p>Completed proposed and certified values are needed. Missing outcomes are not zero reductions.</p>}</div>
  </section>
  <section className="nbr-history"><h2>Neighborhood history &amp; valuation context</h2>
   {a.preliminaryChanges.length?<table className="nbr-table"><thead><tr><th>Proposal years</th><th>Median individual change</th><th>Higher proposals</th><th>Eligible matches</th></tr></thead><tbody>{a.preliminaryChanges.map(x=><tr key={x.current.dataset_id}><th scope="row">{x.prior.tax_year} → {x.current.tax_year}</th><td>{pct(x.medianIndividualPercent)}</td><td>{ratio(x.higher)}</td><td>{x.matchedCount} / {x.baseCount}</td></tr>)}</tbody></table>:<p>Two consecutive preliminary years are needed for proposal changes.</p>}
   {a.carryForward.map(x=><div className="nbr-callout" key={x.current.dataset_id}><h3>Did {x.prior.tax_year} reductions carry forward?</h3><p>{x.reducedCount?`${x.full.count} / ${x.reducedCount} homes reduced at least 10% returned to or above their prior proposal in ${x.current.tax_year}; ${x.partial.count} partly returned and ${x.noReturn.count} did not.`:'No qualifying reduction with all three values is available.'} {x.matchedCount} eligible matches; {x.excludedCount} excluded/unavailable. A review signal, not proof of an incorrect value.</p></div>)}
   {!a.carryForward.length&&<p>Prior proposed and certified values plus the following proposal are needed to assess carry-forward.</p>}
   <div className="nbr-multiplier"><h3>Market-area multiplier: {m?.previous&&m.current?`${m.previous.factor}× → ${m.current.factor}×`:'Unavailable'}</h3><p>The district applies this factor to estimated home and feature rebuilding costs, reduced for age and condition. Land is separate. {m?`${d.market_adjustment!.year} isolated effect: ${money(m.median)} estimated median (${m.count} eligible / ${m.total} included homes).`:'Matched preliminary inputs and published annual factors are unavailable.'} Other inputs held fixed; not the total annual change or tax savings.</p>{d.market_adjustment&&<p className="nbr-note">{d.market_adjustment.history.map(x=>`${x.year}: ${x.filename}, page ${x.page}`).join(' · ')}</p>}</div>
  </section>
 </div>;
}
export function NeighborhoodReportSources({analysis:a}:{analysis:Analysis}) {
 return <section className="nbr-sources"><h2>Source coverage &amp; limits</h2><p>{a.coverage.map(c=>`${c.release.tax_year} ${c.release.roll_stage}, ${dateLabel(c.release.export_date)}: ${c.eligibleCount} / ${c.baseCount} eligible`).join(' · ')||'Historical release coverage unavailable.'}</p><p>Pairs use eligible matches in the current Appraisal District group; conflicting baselines, changed groups and unusable values are excluded. Values precede exemptions and are not taxes. ParcelSavvy is independent of the Appraisal District. Verify official records.</p></section>;
}
