import {fixtureDatabase} from './projection.test.mjs';
import {seedComparisons} from './comparison-fixture.mjs';
import {seedNeighborhood} from './neighborhood-fixture.mjs';
import {seedMarketAdjustments} from './market-adjustment-fixture.mjs';
import {parseMarketAdjustment,adjustmentSummary} from '../../web/src/lib/market-adjustments.ts';
import test from 'node:test';
import assert from 'node:assert/strict';
test('factor estimates require reconciliation and matching; respect RLS and release cutoff',async t=>{
 const db=await fixtureDatabase();t.after(()=>db.close());
 await db.query('select tcad_ingest.publish_property_search($1)',['11111111-1111-4111-8111-111111111111']);
 const {old}=await seedComparisons(db);const {pre}=await seedNeighborhood(db);await seedMarketAdjustments(db);
 await db.exec('set role anon');
 const call=async source=>(await db.query('select public.property_neighborhood_v4($1,$2) r',['100',source??null])).rows[0].r.market_adjustment;
 const raw=await call();const data=parseMarketAdjustment(raw);assert.ok(data);
 const s=adjustmentSummary(data);assert.equal(s.count,2);assert.equal(s.total,5);assert.equal(s.median,112000);
 assert.equal(s.excluded.reduce((n,x)=>n+x.count,0)+s.count,5);
 assert.deepEqual(data.history.map(h=>h.factor),[1.46,1.78]);
 assert.equal(data.homes.find(h=>h.property_id==='100').actual_change,null);
 assert.deepEqual((await call(pre)).homes.filter(h=>h.status==='ok'),data.homes.filter(h=>h.status==='ok'));
 const historical=parseMarketAdjustment(await call(old));assert.equal(historical.history.length,1);assert.equal(adjustmentSummary(historical).median,null);
 assert.equal((await db.query("select public.property_market_adjustment('103') r")).rows[0].r,null);
 const single=parseMarketAdjustment((await db.query("select public.property_market_adjustment('100') r")).rows[0].r);assert.equal(single.homes[0].effect,112000);
 assert.equal(JSON.stringify(raw).includes('PRIVATE'),false);
 await assert.rejects(db.exec('delete from public.neighborhood_market_adjustments'));
 await assert.rejects(db.exec('select * from tcad_ingest.records'));
 const evaluate=async (p,prior,oldPre,f=1.78,oldF=1.46)=>(await db.query('select public.market_adjustment_effect($1,$2,$3,$4,$5,$6) r',[p,prior,oldPre,'TEST',f,oldF])).rows[0].r;
 const snapshot={neighborhood:'TEST',export_date:'2026-04-02',improvement_value:178000,components:[{id:'1',code:'1ST',class_code:'R3',improvement_id:'1',value:100000,area:1200}]};
 const prior={...snapshot,export_date:'2025-04-02',improvement_value:160000};
 assert.deepEqual(await evaluate(snapshot,prior,prior),{status:'ok',effect:32000,actual_change:18000,preliminary_date:'2026-04-02',prior_preliminary_date:'2025-04-02'});
 assert.equal((await evaluate({...snapshot,improvement_value:150000},prior,null)).status,'does_not_reconcile');
 assert.equal((await evaluate(snapshot,{...prior,neighborhood:'RENAMED'},null)).status,'unmatched_neighborhood');
 assert.equal((await evaluate(snapshot,prior,null,null)).status,'missing_factor');
 assert.equal((await evaluate(null,prior,null)).status,'missing_preliminary');
 assert.equal((await evaluate({...snapshot,components:[]},prior,null)).status,'unverified_components');
 assert.equal((await evaluate({...snapshot,components:[{...snapshot.components[0],value:null}]},prior,null)).status,'unverified_components');
 assert.equal((await evaluate({...snapshot,components:[...snapshot.components,{...snapshot.components[0],improvement_id:'2'}]},prior,null)).status,'unverified_buildings');
 assert.equal((await evaluate(snapshot,prior,null,1.78,1.78)).effect,0);
 assert.equal((await evaluate(snapshot,prior,null,1.78,2)).effect,-22000);
 assert.equal(parseMarketAdjustment({...raw,homes:[{...raw.homes[0],effect:Infinity}]}),null);
});
