import {fixtureDatabase} from './projection.test.mjs';
import {seedComparisons} from './comparison-fixture.mjs';
import {seedNeighborhood} from './neighborhood-fixture.mjs';
import {parseNeighborhood} from '../../web/src/lib/supabase/neighborhood.ts';
import {neighborhoodSummary} from '../../web/src/lib/neighborhood.ts';
import test from 'node:test';
import assert from 'node:assert/strict';
test('neighborhood releases, cap outcomes, protest deduplication, and public visibility',async t=>{
 const db=await fixtureDatabase();t.after(()=>db.close());await db.query('select tcad_ingest.publish_property_search($1)',['11111111-1111-4111-8111-111111111111']);const {old}=await seedComparisons(db);const {anchor,pre}=await seedNeighborhood(db);
 await db.exec('set role anon');
 const call=async(source=null)=>(await db.query('select public.property_neighborhood_v2($1,$2) r',['100',source])).rows[0].r;
 const raw=await call();const data=parseNeighborhood(raw,'100');assert.ok(data);
 assert.equal(data.homes.some(h=>h.property_id==='102'||h.property_id==='103'),false);
 assert.equal(JSON.stringify(raw).includes('PRIVATE'),false);
 const s=neighborhoodSummary(data);
 assert.equal(s.all.above.count,2);assert.equal(s.all.above.total,3);
 assert.equal(s.all.reduced.count,2);assert.equal(s.all.reduced.total,3);
 assert.equal(s.all.crossed.count,1);assert.equal(s.all.crossed.total,2);
 assert.equal(s.own.dollars,50000);assert.equal(s.own.percent,10);
 assert.equal(s.protested.count,2);
 assert.equal(data.homes.find(h=>h.property_id==='120').protested,true); // Flag-only informal evidence counts despite a clean certified snapshot.
 assert.equal(data.homes.find(h=>h.property_id==='121').protested,false); // Agent assignment alone does not.
 assert.equal(s.protested.reduced.count,2);assert.equal(s.other.reduced.count,0);
 assert.equal(s.all.averageReduction,125000);
 assert.ok(s.entities.some(e=>e.code==='70'&&!e.applies));
 const early=parseNeighborhood(await call(pre),'100');assert.equal(early.certified_id,null);assert.equal(neighborhoodSummary(early).own,null);
 const historical=parseNeighborhood(await call(old),'100');assert.equal(historical.preliminary_id,null);assert.equal(neighborhoodSummary(historical).protested.count,0);
 assert.equal((await db.query("select public.property_neighborhood_v2('103') r")).rows[0].r.status,'missing_property');
 assert.equal((await db.query('select parcel_comparison.cap_inputs($1,$2,$3) r',[old,pre,['100']])).rows[0].r.length,0);
 await assert.rejects(db.query('select * from tcad_ingest.records limit 1'));
});
test('population v2 separates land-only and other types, retains mixed land coding, and sums residential buildings',async t=>{
 const db=await fixtureDatabase();t.after(()=>db.close());
 await db.query('select tcad_ingest.publish_property_search($1)',['11111111-1111-4111-8111-111111111111']);
 const {old}=await seedComparisons(db);const {anchor,pre}=await seedNeighborhood(db);
 await db.query(`update public.property_snapshot_profiles set snapshot=snapshot||'{"improvement_value":0}'::jsonb where dataset_id=$1 and property_id='122'`,[anchor]);
 await db.query(`update tcad_ingest.records set fields=fields||'{"imprv_state_cd":"A4"}'::jsonb where dataset_id=$1 and prop_id='121' and member_name='neighborhood-types.txt'`,[anchor]);
 await db.query(`update tcad_ingest.records set fields=fields||'{"land_state_cd":"C1"}'::jsonb where dataset_id=$1 and prop_id='120' and member_name='neighborhood-types.txt'`,[anchor]);
 const additions=[{id:'2',improvement_id:'2',code:'1ST',class_code:'R3',area:500,value:50000},{id:'3',improvement_id:'3',code:'1ST',class_code:'R3',area:900,value:0}];
 await db.query(`update public.property_snapshot_profiles set snapshot=jsonb_set(snapshot,'{components}',(snapshot->'components')||$2::jsonb) where dataset_id=$1 and property_id='120'`,[anchor,JSON.stringify(additions)]);
 await db.exec('set role anon');
 const call=async(source=null)=>(await db.query('select public.property_neighborhood_v2($1,$2) r',['100',source])).rows[0].r;
 const raw=await call(),data=parseNeighborhood(raw,'100');assert.ok(data);
 assert.equal(data.homes.length,3);
 assert.equal(data.population.candidate_count,6);
 assert.deepEqual(data.population.excluded,[{property_id:'121',reason:'other_type'},{property_id:'122',reason:'land_only'},{property_id:'123',reason:'unverified_improvements'}]);
 assert.equal(data.population.land_code_mismatch,1);assert.equal(data.population.multiple_buildings,1);
 const mixed=data.homes.find(h=>h.property_id==='120');assert.equal(mixed.area,2500);assert.equal(mixed.certified_area,2500);
 assert.equal(data.caps.some(c=>c.property_id==='121'),false);
 const summary=neighborhoodSummary(data);assert.equal(summary.all.shares.above.total,3);assert.equal(summary.all.shares.reduced.total,3);assert.equal(summary.all.shares.crossed.total,3);
 assert.equal(JSON.stringify(raw).includes('PRIVATE'),false);
 assert.equal(parseNeighborhood({...raw,population:{...raw.population,candidate_count:99}},'100'),null);
 assert.equal(parseNeighborhood({...raw,population:{...raw.population,excluded:[{property_id:'100',reason:'land_only'}]}},'100'),null);
 const early=parseNeighborhood(await call(pre),'100');assert.ok(early.homes.some(h=>h.property_id==='121'));
 assert.ok(parseNeighborhood(await call(old),'100').homes.some(h=>h.property_id==='120'));
 assert.deepEqual((await db.query('select parcel_comparison.neighborhood_types($1,$2,$3) r',[old,anchor,['100']])).rows[0].r,[]);
 assert.deepEqual((await db.query('select parcel_comparison.neighborhood_types($1,$2,$3) r',[anchor,anchor,['102','103']])).rows[0].r,[]);
 await assert.rejects(db.query('select parcel_comparison.neighborhood_types($1,$2,$3)',[anchor,anchor,['bad-id']]));
 await assert.rejects(db.query('select * from tcad_ingest.records limit 1'));
 const area=async components=>(await db.query('select public.neighborhood_floor_area($1) r',[{components}])).rows[0].r.area;
 assert.equal(await area([{code:'1ST',class_code:'R3',improvement_id:'1',area:100,value:null}]),null);
 assert.equal(await area([{code:'1ST',class_code:'R3',improvement_id:'1',area:null,value:100}]),null);
});
