import test from 'node:test';
import assert from 'node:assert/strict';
import {fixtureDatabase} from './projection.test.mjs';
const id='11111111-1111-4111-8111-111111111111';
const actor='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',session='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb';
const submit=(db,message='Compare values across my neighborhood.',category='metric')=>db.query('select public.submit_feature_suggestion($1,$2,$3) saved',[id,category,message]);
test('anonymous submissions are bounded, private and idempotent, with server-owned timestamps',async t=>{
 const db=await fixtureDatabase();t.after(()=>db.close());
 await db.exec('set role anon');
 for(const [message,category] of [['short','feature'],['x'.repeat(2001),'metric'],['valid suggestion here','admin']]) await assert.rejects(submit(db,message,category));
 assert.equal((await submit(db)).rows[0].saved,true);
 assert.equal((await submit(db,'A changed retry must not overwrite.')).rows[0].saved,true);
 for(const sql of ['select * from parcel_feedback.suggestions','select public.admin_suggestions()',"update parcel_feedback.suggestions set message='Overwritten message'",'delete from parcel_feedback.suggestions',"insert into parcel_feedback.suggestions(submission_id,category,message,created_at) values(gen_random_uuid(),'feature','Fake timestamp text',now())"]) await assert.rejects(db.query(sql));
 await db.exec('reset role');
 const rows=(await db.query('select * from parcel_feedback.suggestions')).rows;
 assert.equal(rows.length,1);assert.equal(rows[0].message,'Compare values across my neighborhood.');
 assert.ok(rows[0].created_at);
 assert.equal((await db.query("select prosecdef from pg_proc where oid='public.submit_feature_suggestion(uuid,text,text)'::regprocedure")).rows[0].prosecdef,false);
});
test('inbox requires verified admin and live session; bounded pagination hides submission tokens',async t=>{
 const db=await fixtureDatabase();t.after(()=>db.close());
 await db.query('insert into auth.users(id,email_confirmed_at) values($1,now())',[actor]);
 await db.query('insert into auth.sessions(id,user_id) values($1,$2)',[session,actor]);
 await db.query("select set_config('request.jwt.claim.sub',$1,false),set_config('request.jwt.claims',$2,false)",[actor,JSON.stringify({session_id:session})]);
 await db.exec('set role authenticated');await assert.rejects(db.query('select public.admin_suggestions()'));
 await db.exec('reset role');await db.query('insert into parcel_admin.members(user_id) values($1)',[actor]);
 await db.query("insert into parcel_feedback.suggestions(submission_id,category,message) select gen_random_uuid(),'feature','Suggestion number '||n from generate_series(1,51) n");
 await db.exec('set role authenticated');
 const first=(await db.query('select public.admin_suggestions(0) inbox')).rows[0].inbox;
 assert.equal(first.items.length,50);assert.equal(first.has_more,true);
 assert.equal(first.items[0].message,'Suggestion number 51');assert.ok(!('submission_id' in first.items[0]));
 const next=(await db.query('select public.admin_suggestions(1) inbox')).rows[0].inbox;
 assert.equal(next.items.length,1);assert.equal(next.has_more,false);assert.equal(next.items[0].message,'Suggestion number 1');
 await assert.rejects(db.query('select public.admin_suggestions(-1)'));
 await assert.rejects(db.query('select public.admin_suggestions(1000)'));
 await assert.rejects(db.query('select * from parcel_feedback.suggestions'));
 await db.exec('reset role');await db.query('delete from auth.sessions where id=$1',[session]);
 await db.exec('set role authenticated');await assert.rejects(db.query('select public.admin_suggestions()'));
});
